- README.md
Simple change taken from https://github.com/terraform-providers/terraform-provider-aws/commit/cd869b89cee68382f55faef484c3bb11b5406d32
> fixes image link

- README.md
Simple fix taken from https://github.com/terraform-providers/terraform-provider-aws/commit/94e32c29b7bd8e8c98828f63d21eb4bc094f80ae
> updates readme with proper paths for this provider

- website/docs/r/monitor.html.markdown
for https://github.com/terraform-providers/terraform-provider-datadog/issues/21 and https://github.com/terraform-providers/terraform-provider-datadog/issues/7
Closes #21
> update docs with composite

- website/docs/r/timeboard.html.markdown
Fixes #22 by adding documentation for conditional format
> Add conditional_format documentation

- vendor/gopkg.in/zorkian/go-datadog-api.v2/README.md
- vendor/gopkg.in/zorkian/go-datadog-api.v2/client.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/dashboards.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/datadog-accessors.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/hosts.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/monitors.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/request.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/screenboards.go
- vendor/vendor.json
Update our vendored version of gopkg.in/zorkian/go-datadog-api.v2 to use
the version 2.6 release, which has the fix we need for #31.
> Update the client to the 2.6 release.

- vendor/gopkg.in/zorkian/go-datadog-api.v2/datadog-accessors.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/monitors.go
- vendor/vendor.json
Update our vendored version of gopkg.in/zorkian/go-datadog-api.v2 to use
the version 2.7 release, which has the fix we need for #33
> Update the client to the 2.7 release.

- datadog/resource_datadog_monitor.go
- datadog/resource_datadog_monitor_test.go
This fixes #3 / https://github.com/hashicorp/terraform/issues/13784.
Fixed as initially suggested by @kmshultz, thanks for bringing this up!
> Fixes Datadogs API quirk described in #3

- datadog/resource_datadog_monitor.go
> new_host_delay should not be computed

- CHANGELOG.md
Update the changelog to reflect changes that will be shipped with 1.3.0
> Prepare 1.3.0

- datadog/resource_datadog_monitor.go
Fixes #41, see issue for context.
> Explicitly silent a monitor when needed

- datadog/resource_datadog_screenboard.go
Without this running `terraform apply` would result in a panic:
```
panic: interface conversion: interface {} is string, not float64
[...]
...datadog.setJSONNumberFromDict...
```
> Fix fill_min and fill_max panic issue

- CHANGELOG.md
Update changelog with support of Synthetics resources
> Update changelog with support of Synthetics resources

- datadog/resource_datadog_monitor_test.go
Adds a test for functionality implemented in #131
> Add tests for datadog_monitor resource threshold_windows attribute

- datadog/resource_datadog_monitor.go
- datadog/resource_datadog_monitor_test.go
- go.mod
- go.sum
- vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
- vendor/github.com/zorkian/go-datadog-api/monitors.go
- vendor/modules.txt
- website/docs/r/downtime.html.markdown
- website/docs/r/monitor.html.markdown
See #181 for detailed explanation of the problem.
> Fix and provide better docs for (un)muting monitors. Fixes #181

- website/docs/r/timeboard.html.markdown
This was enabled by TF 0.12 feature called dynamic blocks: https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks
> Add example on constructing dynamic timeboards. Fixes #47, #64.

- website/docs/r/examples/monitors.html.markdown
Add an anomaly monitor example to the docs.
> Add an examply of an anomaly monitor

- CHANGELOG.md
Prep the changelog for the 2.0.2 provider release
> Prep 2.0.2 release

- datadog/import_datadog_downtime_test.go
- datadog/resource_datadog_monitor_test.go
* downtime import test broken by PR #264
* monitor update tests broken by PR #247
> Fix integration tests

- datadog/resource_datadog_downtime.go
This is a followup to #264, which made the provider ignore drifts in start/end attributes for resources. This PR makes sure that the drifts are detected and fixed properly.
> Make sure downtime resource properly fixes state drifts in start/end attributes

- CHANGELOG.md
Do the changelog for the 2.1.0 Release of our Terraform Provider.
> Prep 2.1.0 Release

- website/docs/r/examples/monitors.html.markdown
Create an example of a process monitor in the Monitor Examples page of the TF Provider docs
> Add example Process Monitor

- go.mod
- go.sum
- vendor/github.com/zorkian/go-datadog-api/app_keys.go
- vendor/github.com/zorkian/go-datadog-api/boards.go
- vendor/github.com/zorkian/go-datadog-api/dashboards.go
- vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
- vendor/github.com/zorkian/go-datadog-api/helpers.go
- vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
- vendor/github.com/zorkian/go-datadog-api/service_level_objectives.go
- vendor/github.com/zorkian/go-datadog-api/synthetics.go
- vendor/modules.txt
Upgrade the go zorkian client to v2.22.0
First time upgrading this, ran the following:
go get github.com/zorkian/go-datadog-api@v2.22.0
go mod vendor
go mod tidy
> Update go client

- CHANGELOG.md
> Update changelog for 2.2.0 release

- CHANGELOG.md
Fix up the 2.2.0 changelog formatting.
> Add bullet formatting to changelog 

- go.mod
- go.sum
- vendor/github.com/zorkian/go-datadog-api/board_widgets.go
- vendor/github.com/zorkian/go-datadog-api/client.go
- vendor/github.com/zorkian/go-datadog-api/dashboard_list_items_v2.go
- vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
- vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
- vendor/modules.txt
Update the go client to the latest master
Needed for some open PRs
Will update to an official release prior to the next provider release.
> Update go api client dep to latest master

- go.mod
- go.sum
- vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
- vendor/github.com/zorkian/go-datadog-api/users.go
- vendor/modules.txt
> Update the zorkian client dep to v2.23.0

- CHANGELOG.md
Update the changelog for the 2.3.0 release
> Prep 2.3.0 release

- datadog/resource_datadog_dashboard.go
- datadog/resource_datadog_dashboard_test.go
* Add support for Type
* Add support for Events
* Add support for YAxis
> Add full support for timeseries definitions

- website/docs/r/service_level_objective.html.markdown
This is an attempt to fix formatting issues on terraform.io/docs which [does not match github's rendering](https://imgur.com/a/hMjmsSc)
> Add spacing

- datadog/resource_datadog_screenboard.go
- datadog/resource_datadog_timeboard.go
- datadog/validators.go
Picks up where we left off in #129
> add 'count' as valid aggregation method

- datadog/resource_datadog_logs_custom_pipeline.go
- datadog/resource_datadog_logs_custom_pipeline_test.go
- website/docs/r/logs_custom_pipeline.html.markdown
Support:
- Geo IP parser
- String builder processor
- `samples` from Grok parser.
-  update related documentation.
> Support all processors in Logs pipeline

- website/docs/r/service_level_objective.html.markdown
> Fix example for importing SLO

- website/docs/r/monitor.html.markdown
Add a note stating the monitor type cannot be updated.
> Monitor type note

- CHANGELOG.md
Based on https://github.com/terraform-providers/terraform-provider-datadog/compare/v2.5.0...master
> Prepare 2.6 release

- website/docs/r/monitor.html.markdown
> Improve monitor example with ignoring changes on silenced

- datadog/cassettes/TestAccDatadogLogsPipeline_basic.yaml
- datadog/resource_datadog_logs_custom_pipeline.go
- datadog/resource_datadog_logs_custom_pipeline_test.go
- website/docs/r/logs_custom_pipeline.html.markdown
> LI-104: Add support for lookup processor

- datadog/cassettes/TestAccDatadogIntegrationAWSLogCollection.yaml
- datadog/resource_datadog_integration_aws.go
- datadog/resource_datadog_integration_aws_log_collection.go
- datadog/resource_datadog_integration_aws_log_collection_test.go
- datadog/resource_datadog_logs_index.go
- datadog/resource_datadog_monitor.go
- datadog/resource_datadog_service_level_objective.go
This PR updates the aws_log_collection resource to utilize the Datadog Go Client
> Update aws_log_collection resource to use Datadog Go client

- datadog/resource_datadog_dashboard.go
> Add support for tags_execution

- website/docs/r/dashboard.html.markdown
> Add support for tags_execution - Doc update

- datadog/data_source_datadog_ip_ranges.go
Uses correct response value with IP addresses for each service.
closes #537
> Fix data source for IPRanges

- datadog/resource_datadog_monitor.go
- website/docs/r/monitor.html.markdown
Fixes https://github.com/terraform-providers/terraform-provider-datadog/issues/519
> Add monitor force_delete parameter

- datadog/cassettes/TestAccDatadogDashboardServiceMap.yaml
- datadog/cassettes/TestAccDatadogDashboardServiceMap_import.yaml
- datadog/resource_datadog_dashboard.go
- datadog/resource_datadog_dashboard_service_map_test.go
Fixes https://github.com/terraform-providers/terraform-provider-datadog/issues/467
> Add ServiceMap widget to datadog_dashboard

- GNUmakefile
- datadog/cassettes/TestAccDatadogDashboardLogStream.yaml
- datadog/cassettes/TestAccDatadogDashboardLogStreamLogSet.yaml
- datadog/cassettes/TestAccDatadogDashboardLogStreamLogSet_import.yaml
- datadog/cassettes/TestAccDatadogDashboardLogStream_import.yaml
- datadog/resource_datadog_dashboard_log_stream_test.go
Related to https://github.com/terraform-providers/terraform-provider-datadog/issues/392
> Add logset test scenario for log stream widget

- datadog/cassettes/TestAccDatadogIntegrationAzure.yaml
- datadog/resource_datadog_integration_azure.go
- datadog/resource_datadog_integration_azure_test.go
- website/datadog.erb
- website/docs/r/integration_azure.html.markdown
Adding Datadog Azure Integration Terraform Resource
Fixes https://github.com/terraform-providers/terraform-provider-datadog/issues/196
> Add Azure TF resource

- datadog/provider.go
`TF_LOG=TRACE TF_LOG_PATH=/dev/stdout terraform apply` 🎉
> Respect TF_LOG for debug output

- datadog/resource_datadog_service_level_objective.go
Ignore space differences for trimmed values.
closes #334
> Synchronize state and diff function for trimmed fields

- website/docs/r/synthetics.html.markdown
This migrates the doc to the new format, document `targetjsonpath` and
explains the migration.
> Add doc about new assertion format

- website/docs/r/logs_archive.html.markdown
> Mention imports in logs archive docs

- datadog/cassettes/TestAccDatadogIntegrationPagerdutyServiceObject_Basic.yaml
- datadog/cassettes/TestAccDatadogIntegrationPagerduty_Basic.yaml
- datadog/cassettes/TestAccDatadogIntegrationPagerduty_Migrate2ServiceObjects.yaml
- datadog/cassettes/TestAccDatadogIntegrationPagerduty_TwoServices.yaml
- datadog/resource_datadog_integration_pagerduty_test.go
With the removal of the delete tests were broken.
> Fix pagerduty integration tests

- GNUmakefile
> Use gotestsum

- docs/resources/dashboard.md
Also marks logset as deprecated.
Closes #614
> Update docs for indexes in the stream widget.

- datadog/resource_datadog_dashboard.go
Fix some tiny typo and mistakes in an error message.
> Fix tiny mistakes in an error message

- .pre-commit-config.yaml
Use local version of prettier pre-commit hook configuration
> Use locally defined prettier pre commit hook config

- go.mod
- go.sum
- vendor/github.com/DataDog/datadog-api-client-go/.apigentools-info
- vendor/github.com/DataDog/datadog-api-client-go/CHANGELOG.md
- vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/api_events.go
- vendor/github.com/DataDog/datadog-api-client-go/version.go
- vendor/modules.txt
> Update to released go client

- docs/resources/monitor.md
> Document monitor priority

- datadog/resource_datadog_role.go
- docs/resources/role.md
This fixes the reference in the doc, and make it possible to create a
read-only role.
> Small fixes to roles resource

- docs/index.md
Add a note about how to declare the provider to use the Terraform Registry when using terraform 0.13 and greater.
> Add example for initializing provider with tf 0.13+

- docs/resources/synthetics_test.md
> Fix typo in synthetics doc

- datadog/resource_datadog_dashboard.go
> Fix typo: updateDashboarLists -> updateDashboardLists

- datadog/resource_datadog_monitor.go
Intermittent server 502 errors can happen during validation or retrieval of monitors. This should help not failing entire terraform plan/apply runs by doing a few retries of those calls.
Timeout relatively short at 1 minute so as not to hang too long on real server downtime.
> Add retry on 502 for monitor get and validate

- datadog/resource_datadog_dashboard.go
- docs/resources/dashboard.md
Quite a few query argument were not referenced properly
> Fix documentation of request widget fields

- datadog/resource_datadog_integration_aws.go
> Make datadog_integration_aws' description not a deprecation warning

- CHANGELOG.md
> Changelog for 2.19.1

- datadog/resource_datadog_monitor.go
- datadog/resource_datadog_user.go
- docs/data-sources/monitor.md
- docs/guides/monitors.md
- docs/index.md
- docs/resources/logs_archive.md
- docs/resources/logs_metric.md
- docs/resources/monitor.md
- docs/resources/user.md
- examples/guides/anomaly_monitor.tf
- examples/guides/composite_monitor.tf
- examples/guides/process_monitor.tf
- examples/resources/datadog_logs_archive/resource.tf
- examples/resources/datadog_logs_metric/resource.tf
- examples/resources/datadog_user/resource.tf
This fixes some issues mostly in the monitor resource.
> Fixes to generated documentation

- docs/data-sources/synthetics_locations.md
- docs/resources/synthetics_global_variable.md
- docs/resources/synthetics_private_location.md
- docs/resources/synthetics_test.md
- examples/data-sources/datadog_synthetics_locations/data-source.tf
- examples/resources/datadog_synthetics_global_variable/import.sh
- examples/resources/datadog_synthetics_global_variable/resource.tf
- examples/resources/datadog_synthetics_private_location/import.sh
- examples/resources/datadog_synthetics_private_location/resource.tf
- examples/resources/datadog_synthetics_test/import.sh
- examples/resources/datadog_synthetics_test/resource.tf
Use tfplugindocs (see #798) to generate the synthetics documentation
> Generate synthetics documentation

- docs/resources/logs_index.md
- docs/resources/logs_index_order.md
- examples/resources/datadog_logs_index/import.sh
- examples/resources/datadog_logs_index/resource.tf
- examples/resources/datadog_logs_index_order/import.sh
- examples/resources/datadog_logs_index_order/resource.tf
Generate documentation for logs index resources using tfplugindocs
> Generate logs index documentation

- go.mod
- go.sum
This includes the sdk fix at
https://github.com/hashicorp/terraform-plugin-sdk/pull/659
Closes #781
> Use latest commit of fork

- docs/resources/metric_metadata.md
- examples/resources/datadog_metric_metadata/resource.tf
Generate documentation for the metrics_metadata resource using tfplugindocs
> Generate metrics_metadata docs

- docs/resources/role.md
- examples/resources/datadog_role/import.sh
- examples/resources/datadog_role/resource.tf
Generate documentation for the roles resource using tfplugindocs
> Generate docs for role resource

- datadog/resource_datadog_integration_pagerduty.go
- datadog/resource_datadog_integration_pagerduty_service_object.go
- docs/resources/integration_pagerduty_service_object.md
- examples/resources/datadog_integration_pagerduty/resource.tf
- examples/resources/datadog_integration_pagerduty_service_object/resource.tf
Generate the pagerduty resource docs using tfplugindocs
> Generate pagerduty resource docs

- docs/resources/dashboard.md
- docs/resources/monitor.md
Generate with the latest code on master. 
This includes a field on monitors and the extra Deprecation line we added that wasn't yet used on the dashboard docs
> Generate with latest master

- datadog/resource_datadog_screenboard.go
> [screenboard] Fix outdated description

- datadog/resource_datadog_dashboard_test.go
Just the dashboard retry from - https://github.com/DataDog/terraform-provider-datadog/pull/919/files
> Retry the dashbaord resource

- DEVELOPMENT.md
Updates the Prerequisites section to include a note regarding `gotestsum`.
> Update DEVELOPEMENT.md to include section regarding gotestsum

- datadog/tests/resource_datadog_dashboard_test.go
- datadog/tests/resource_datadog_monitor_test.go
Update dashboard test destroy helper to make 5xx also retry
Bump the retry count to be 10
Add the retry helper to the monitor delete helper
This only impacts the test framework
> Bump dash retry and add retry to monitor

- LICENSE-3rdparty.csv
- go.mod
- go.sum
> update go client to beta 16

- docs/resources/synthetics_test.md
Regenerate synthetics docs from the contribution in #964
> Regenerate synthetics docs

- docs/data-sources/monitor.md
- docs/index.md
- docs/resources/integration_slack_channel.md
- docs/resources/monitor.md
Regenerate documentation from latest `master` using `tfplugindocs. 
This should allow #967 to pass
> Regenerate documentation

- .github/workflows/test.yml
- GNUmakefile
- datadog/internal/utils/utils.go
- datadog/tests/resource_datadog_integration_slack_channel_test.go
> Fix lint reporting

- datadog/resource_datadog_integration_slack_channel.go
Closes: https://github.com/DataDog/terraform-provider-datadog/issues/978
> Use mutex with slack channels resource

- GNUmakefile
- main.go
- scripts/fmtcheck.sh
Use `goimports` along with -local flag to format files and imports within them.
> Use goimports instead of gofmt

- docs/resources/logs_metric.md
- examples/resources/datadog_logs_metric/resource.tf
Make it more explicit that this is a block list
Closes #1009
> Add group_by block to logs_metric example

- datadog/resource_datadog_logs_custom_pipeline.go
Creating, updating or deleting logs custom pipelines in parallel can return api errors. This pr adds mutex to the resource to limit parallelism to 1.
> Add mutex to logs custom pipeline resource

- CHANGELOG.md
> Prepare release of 2.26.0

- docs/resources/dashboard.md
- examples/resources/datadog_dashboard/resource.tf
The provide examples were not directly runnable.
> Update dashboard examples

- CHANGELOG.md
> Add changelog for 3.1.0

- CHANGELOG.md
> Add changelog for 3.1.1

- CHANGELOG.md
> Add changelog for 3.1.2 release

- docs/resources/synthetics_test.md
- examples/resources/datadog_synthetics_test/resource.tf
> Add multistep API test example

- datadog/resource_datadog_dashboard_json.go
Fixes: https://github.com/DataDog/terraform-provider-datadog/issues/1166
> Use custom SendRequest method to get a dashboard

- docs/resources/logs_custom_pipeline.md
- docs/resources/logs_integration_pipeline.md
- examples/resources/datadog_logs_custom_pipeline/import.sh
- examples/resources/datadog_logs_integration_pipeline/import.sh
> Document how to find pipeline ID for import

- datadog/resource_datadog_synthetics_test_.go
> Properly handle nil basicAuth values

- datadog/resource_datadog_slo_correction.go
- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
- go.mod
- go.sum
New required attribute broke constructor in synthetics assertions, and add nullable to two fields in slo correction
> Bump go client and make necessary fixes

- .azure-pipelines/all.yml
> Enable http retries on azp tests

- datadog/resource_datadog_monitor.go
- docs/resources/monitor.md
Updates the `new_group_delay` and `new_host_delay` docs to resolve #1292
> `new_group_delay` and `new_host_delay` docs

- CHANGELOG.md
> Prepare for v3.7.0 release

- datadog/resource_datadog_slo_correction.go
- docs/resources/slo_correction.md
Updated SLO recurring correction documentation with list of supported rules
> [SLO corrections] Update documentation to list supported correction rules

- datadog/resource_datadog_security_monitoring_default_rule.go
- datadog/resource_datadog_security_monitoring_rule.go
UI supports more now.
Closes #1310
> Raise the case limit in security rules

- .github/workflows/changelog.yaml
- DEVELOPMENT.md
We need a changelog and a resource label to generate proper changelog
entries.
> Enforce labels on PRs

- datadog/resource_datadog_authn_mapping.go
- datadog/tests/resource_datadog_authn_mapping_test.go
Supports UpdateContext for Datadog SAML Authentication Mapping
> [ACCESS-598] Support UpdateContext for Datadog SAML Authentication Mapping

- CHANGELOG.md
> Prepare changelog for 3.9.0 release

- .github/workflows/changelog.yaml
Move to a label to title prefix.
> Validate PR title

- .github/release.yml
- .github/workflows/prepare_release.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/test_integration.yml
- .goreleaser.yml
This adds an action to create the changelog PR, and automatically push
the tag based on its merge.
> Automatize the release process

- datadog/resource_datadog_dashboard.go
> Remove duplicate custom-links building

- datadog/resource_datadog_downtime.go
- docs/resources/downtime.md
I got a bit stuck getting this to work until I read the source. Updating the docs here to make it clear how to use rrule
> docs: Update docs for rrule/type

- datadog/resource_datadog_monitor_json.go
- go.sum
Closes: https://github.com/DataDog/terraform-provider-datadog/issues/1445
> [datadog_monitor_json] Avoid unnecessary restricted_roles diff

- .github/workflows/changelog.yaml
Fixes issues related to updating PR title but the check keeps failling.
> Trigger PR title check on edit

- go.mod
- go.sum
> Use client release 1.15

- go.mod
- go.sum
> [provider] Update go client

- datadog/resource_datadog_synthetics_private_location.go
Don't crash when the list is empty and don't show an perpetual diff.
Closes #1476
> [datadog_synthetics_private_location] Improve restricted_roles handling

- datadog/internal/transport/custom_transport.go
Closes: https://github.com/DataDog/terraform-provider-datadog/issues/1531
> [provider] Handle redirects by retaining the original request/redirect body

- datadog/resource_datadog_rum_application.go
- docs/resources/rum_application.md
Minor documentation fix.
A follow-up on https://github.com/DataDog/terraform-provider-datadog/pull/1537
> RUM App support: Minor doc fix

- datadog/resource_datadog_dashboard.go
> [datadog_dashboard] Handle empty requests definition in hostmap widget

- datadog/tests/provider_test.go
- datadog/tests/resource_datadog_downtime_test.go
> Fix failing downtime integration tests

- datadog/provider.go
Closes: https://github.com/DataDog/terraform-provider-datadog/issues/1559
> [datadog_ip_ranges] Fix `IPRanges` server configuration

- go.mod
- go.sum
> Bump `datadog-api-client` to v2.4.0

- datadog/resource_datadog_monitor.go
> [datadog_monitor] Handle explicit null for `new_host_delay`

- datadog/resource_datadog_dashboard.go
Closes: https://github.com/DataDog/terraform-provider-datadog/issues/1596
> [datadog_dashboard] Suppress URL attribute diff

- datadog/resource_datadog_downtime.go
- docs/resources/downtime.md
> [datadog_downtime] Specify downtime start/end and timezone format

- datadog/provider.go
- docs/index.md
Closes: https://github.com/DataDog/terraform-provider-datadog/issues/1573
> Add more `site` examples and link to site docs page

- datadog/tests/data_source_datadog_logs_archives_order_test.go
- docs/resources/service_level_objective.md
- examples/resources/datadog_service_level_objective/resource.tf
> Fix slo examples by removing computed fields

- docs/resources/dashboard.md
- docs/resources/security_monitoring_rule.md
- go.mod
- go.sum
> [provider] Upgrade Go client to v2.8.0

- datadog/resource_datadog_service_level_objective.go
- docs/resources/service_level_objective.md
Docs are not clear about which field is used to specify the primary time frame.
> [datadog_service_level_objectives] Update docs to clarify primary time frame fields

- docs/resources/logs_index_order.md
- examples/data-sources/datadog_logs_indexes_order/data-source.tf
- examples/resources/datadog_logs_index_order/import.sh
Followup to https://github.com/DataDog/terraform-provider-datadog/pull/1575
> Clarify logs index order name

- datadog/internal/validators/validators.go
- datadog/resource_datadog_security_monitoring_rule.go
> [datadog_security_monitoring_rule] Don't cast nil values in `group_by_fields` or `distinct_fields`

- datadog/resource_datadog_security_monitoring_rule.go
- datadog/resource_datadog_synthetics_test_.go
- docs/resources/security_monitoring_rule.md
- docs/resources/synthetics_test.md
> [datadog_synthetics/security_monitoring_rule] Add time units to synthetics and security monitoring rules

- datadog/resource_datadog_sensitive_data_scanner_group.go
- datadog/resource_datadog_sensitive_data_scanner_rule.go
Fixes concurrency issues with the endpoint
> [datadog_sensitive_data_scanner] Add mutex to SDS resource

- datadog/resource_datadog_monitor.go
> [datadog_monitor] Fix panic on scheduling option with empty evaluation window

- docs/resources/synthetics_test.md
- examples/resources/datadog_synthetics_test/resource.tf
CI somehow missed this on the original PR, maybe because it was on a fork?
> [datadog_synthetics_test] Format synthetics examples

- DEVELOPMENT.md
- datadog/tests/provider_test.go
> Add support for configuring api url in tests

- datadog/resource_datadog_synthetics_test_.go
SSIA. Occurs if synthetic test basicauth options are configured outside of terraform, and optional fields are uninitialized.
Found while debugging #1942
> [datadog_synthetics_test] Fix segfault on uninitialized basic auth fields

- datadog/resource_datadog_dashboard_json.go
> [datadog_dashboard_json] Check if widgets are valid while casting

- go.mod
- go.sum
> [provider] Bump Datadog Go SDK to 2.15.0

- datadog/fwprovider/resource_datadog_restriction_policy.go
- docs/resources/restriction_policy.md
> [datadog_restriction_policy] remove version mention from docs

- .github/workflows/test.yml
We run certain steps multiple times across different terraform versions. Lets move them out to their own steps.
> Deduplicate Github action jobs

- docs/index.md
- templates/index.md.tmpl
> Fix tutorial link

- datadog/resource_datadog_integration_aws_tag_filter.go
> [datadog_integration_aws_tag_filter] Prevent concurrency issues with mutex

- datadog/resource_datadog_sensitive_data_scanner_group.go
- docs/resources/sensitive_data_scanner_group.md
> [datadog_sensitive_data_scanner_group] Avoid panic when nil returned

- docs/resources/integration_confluent_account.md
- examples/resources/datadog_integration_confluent_account/import.sh
Followup to: https://github.com/DataDog/terraform-provider-datadog/issues/2105
> [datadog_integration_confluent_account] Add note about Confluent Account import

- datadog/resource_datadog_integration_pagerduty_service_object.go
Follow up to https://github.com/DataDog/terraform-provider-datadog/pull/2120 to make sure the doc source is changed
> [integration_pagerduty_service_object] Fix docs

- CHANGELOG.md
This reverts commit 628e11a7d16f84a641f8b223c3ca11380d6933cc.
> Revert "Update CHANGELOG (#2163)"

- docs/guides/monitors.md
- examples/guides/watchdog_monitor.tf
Update the example for Watchdog monitor
> Update Watchdog monitor example

- datadog/resource_datadog_synthetics_test_.go
prevent panic from casting a nil
> [datadog_synthetics_test] Check if ci options block is valid

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
Addressing comment in https://github.com/DataDog/terraform-provider-datadog/pull/2273
> [datadog_synthetics_test] Small doc style change

- .github/CODEOWNERS
The Synthetics Continuous Testing team will soon take ownership of Terraform for Synthetics.
For now, since the Synthetics App team still has some Jira cards assigned and the knowledge of Terraform for Synthetics, let's co-own the code 😁
> [codeowners] Add Synthetics CT team

- datadog/resource_datadog_monitor.go
- docs/resources/monitor.md
Fix panic when eval window is empty
> [datadog_monitor] Check eval window cast before using

- datadog/resource_datadog_logs_archive.go
> [datadog_logs_archive] Remove required check for `project_id`

- datadog/fwprovider/resource_datadog_openapi_api.go
- docs/resources/openapi_api.md
- examples/resources/datadog_openapi_api/resource.tf
Review the existing docs and add some missing context / rephrase some parts
> [datadog_openapi_api] Update documentation

- datadog/fwprovider/resource_datadog_security_monitoring_suppression.go
> [datadog_security_monitoring_suppression] Fix error handling when creating suppression payload

- README.md
> [repo] Fix badge and image in readme

- datadog/fwprovider/resource_datadog_integration_gcp_sts.go
Add a mutex around the calls that make modifications to GCP STS. There have been times when the concurrency of the mutating calls have resulted in the API calls in a nebulous state.
> [datadog_integration_gcp_sts] Add a mutex around the mutating calls in the GCP STS module

- datadog/resource_datadog_security_monitoring_rule.go
- go.mod
- go.sum
Fixes https://datadoghq.atlassian.net/browse/APITL-921
> [datadog_security_monitoring_rule] Upgrade go client.

- datadog/resource_datadog_logs_index.go
- docs/resources/logs_index.md
> [datadog_logs_index] Set index name to replace on modify

- .github/CODEOWNERS
Fixing our `CODEOWNERs` to that the correct owners are tagged in PR reviews.
> [Repo] Update CODEOWNERS for dashboards resources

- docs/resources/team_link.md
- examples/resources/datadog_team_link/resource.tf
Update the example in docs to make the position parameter match the variable type.
> [datadog_team_link] Fix example of position field

- docs/resources/security_monitoring_suppression.md
- examples/resources/datadog_security_monitoring_suppression/resource.tf
Update example in docs to make `data_exclusion_query` more visible.
> [security_monitoring_suppression] Update example in docs

- docs/resources/restriction_policy.md
- docs/resources/sensitive_data_scanner_group.md
- docs/resources/sensitive_data_scanner_rule.md
- examples/resources/datadog_restriction_policy/import.sh
- examples/resources/datadog_sensitive_data_scanner_group/import.sh
- examples/resources/datadog_sensitive_data_scanner_rule/import.sh
> [documentation] Fix import examples with empty string IDs

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/dashboard.md
- docs/resources/monitor.md
- docs/resources/powerpack.md
- go.mod
- go.sum
update go.mod and go.sum to have the latest updates from api-client-go and change monitor.md file to reflect this changes.
> [provider] Bump datadog-api-client to latest master

- datadog/fwprovider/framework_provider.go
- datadog/internal/utils/utils.go
- datadog/provider.go
Reduce idle connection timeout to 45s from default of 90s.
> [datadog_provider] Reduce idle connection timeout

- datadog/fwprovider/resource_datadog_apm_retention_filter.go
- docs/resources/apm_retention_filter.md
- examples/resources/datadog_apm_retention_filter/resource.tf
Better documentation on syntax of the retention filter query, addressing : https://github.com/DataDog/terraform-provider-datadog/issues/2415
> [datadog_apm_retention_filter] Adds doc and change example

- datadog/fwprovider/framework_provider.go
- datadog/provider.go
- docs/index.md
> [provider] Improve description of api_url to specify the default and requiredness

- datadog/fwprovider/framework_provider.go
- datadog/provider.go
- docs/index.md
> [provider] remove required mention for `api_url` since there is a default

- datadog/resource_datadog_synthetics_test_.go
This PR cleans and organise the code in the synthetics resource file.
It should not change any feature, as it's just moving code around, and renaming functions.
It should be easier to review commit by commit.
Some of the commits move large chunks of code, but don't change anything.
> Organise synthetics resource file

- datadog/resource_datadog_service_level_objective.go
- docs/resources/service_level_objective.md
update description for slo` validate`.
> [SOCE-1320] update description for slo validate option

- datadog/provider.go
> [repo] Add comment mentioning sdkv2 deprecation

- CHANGELOG.md
Reverts DataDog/terraform-provider-datadog#2600
> Revert "Release 3.45.0"

- .github/workflows/release.yml
> Remove workflows permission.

- datadog/fwprovider/resource_datadog_user_role.go
This PR simplifies the logic in `datadog_user_role` as preparation for a change of approach in #2609
> [datadog_user_role] refactor

- datadog/fwprovider/resource_datadog_integration_aws_account.go
Fixes incorrect error message reported by https://github.com/DataDog/terraform-provider-datadog/issues/2739
> [datadog_integration_aws_account] Fix error message wording

- datadog/fwprovider/resource_datadog_azure_integration.go
- docs/resources/integration_azure.md
Picking up where review left off on https://github.com/DataDog/terraform-provider-datadog/pull/2738
> [datadog_azure_integration] Support metric filitering

- datadog/fwprovider/resource_datadog_azure_integration.go
- docs/resources/integration_azure.md
Reverts DataDog/terraform-provider-datadog#2757
temporarily reverting for bugfix release — will reintroduce changes in subsequent PR
> Revert "[datadog_azure_integration] Support metric filitering"

- .github/workflows/changelog.yaml
- .github/workflows/prepare_release.yml
- .github/workflows/release.yml
- .github/workflows/sdkv2_deprecation.yaml
- .github/workflows/test.yml
- .github/workflows/test_integration.yml
https://datadoghq.atlassian.net/browse/AWF-59
> Set the SHA hash for the GitHub actions.

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
Follow up to https://github.com/DataDog/terraform-provider-datadog/pull/2772
> [datadog_synthetics_test] duplication of default info

- .generator/src/generator/cli.py
- .generator/src/generator/setup.py
- .generator/src/generator/templates/delete_method.j2
- .generator/src/generator/utils.py
Have a more legible codebase to make contributions easier.
Breaking up code into smaller functions. 
Breaking up code into appropriate files.
> [TIDY] (generator) Refactor the generator

- .generator/src/generator/openapi.py
- .generator/src/generator/setup.py
- .generator/src/generator/type.py
This is part of a string of PR designed to refactor the generator's code base.
Moved Type related functions to their own file.
> [TIDY] (generator) Moved type related functions to their own file

- .generator/src/generator/cli.py
The CLI could accept an `output` parameter. This parameter dictated the path in which the files should be generated.
This path was used in a shell command to format the files.
Removing the `output` parameter prevents the user from running arbitrary code in shell when we format the generated files.
- removed the `output` optional parameter from the CLI
> [Generator] (fix) Removed `output` parameter

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
- examples/resources/datadog_synthetics_test/resource.tf
The current documentation lacks an example related to file uploads. 
This PR addresses this issue by adding an example to the documentation.
> [synthetics] Update doc with an example of file upload

- .generator/README.md
- .generator/src/generator/setup.py
- .generator/src/generator/templates/data_source/base.j2
- .generator/src/generator/templates/data_source/types.j2
- .generator/src/generator/type.py
- .generator/src/generator/utils.py
We do not want to generate models for the "relationship" or "included" fields.
- Updated README
- Added a new filter : `clean_response_for_datasource`
- Use this new filter in the templates
> [Generator] (fix) Fixed the way the computed values are generated

- .github/CODEOWNERS
Assign ownership to some integration resources.
> Assign correct ownership for collaboration-integrations

- datadog/resource_datadog_metric_metadata.go
> [datadog_metric_metadata] Fix drift on imported resources

- .github/workflows/test.yml
This makes the tofu test runs consistent with the non-tofu ones. Same approach as in https://github.com/DataDog/terraform-provider-datadog/pull/2811.
> Run all tofu tests for all PRs

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
**What's New / Different**
SYN-4083: Update tick-every description with value ranges for different test types
> [datadog_synthetics_test] SYN-4083: Update tick-every description with value ranges

- datadog/fwprovider/resource_datadog_monitor_notification_rule.go
- docs/resources/monitor_notification_rule.md
**Notes**
- Update `datadog_monitor_notification_rule` docs with preview description
> [datadog_monitor_notification_rule] Update docs with preview description

- datadog/fwprovider/resource_datadog_on_call_escalation_policy.go
Fixes https://github.com/DataDog/terraform-provider-datadog/issues/3069.
> [datadog_on_call_escalation_policy] correctly set retries on update

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
This PR fixes a broken link and aligns 3 similar descriptions.
> [datadog_synthetics_test] Fix link in assertion descriptions

- datadog/fwprovider/resource_datadog_on_call_escalation_policy.go
- datadog/fwprovider/resource_datadog_on_call_schedule.go
- datadog/fwprovider/resource_datadog_on_call_team_routing_rules.go
- docs/resources/on_call_schedule.md
- docs/resources/on_call_team_routing_rules.md
- scripts/generate-docs.sh
Fixes https://github.com/DataDog/terraform-provider-datadog/issues/3055.
Due to https://github.com/hashicorp/terraform-plugin-framework/issues/740, and https://github.com/hashicorp/terraform-plugin-docs/issues/363, we have to manually validate and update the docs.
> [on_call] update validation and documentation

- datadog/fwprovider/resource_datadog_monitor_notification_rule.go
- docs/resources/monitor_notification_rule.md
Remove preview info since the feature is now GA
> [datadog_monitor_notification_rule] remove preview info notif rule

- datadog/tests/cassettes/TestAccDatadogAppKeyRegistrationResource.yaml
- datadog/tests/resource_datadog_app_key_registration_test.go
Context: https://dd.slack.com/archives/C013K2M4KH6/p1752086722848869
> Fix app key registration test

- datadog/fwprovider/observability_pipeline/custom_processor.go
API spec implementation: https://github.com/DataDog/datadog-api-spec/pull/4187
> [datadog_observability_pipeline] make CustomProcessor `enabled` and `drop_on_error` fields required

- docs/resources/synthetics_test.md
- examples/resources/datadog_synthetics_test/resource.tf
> [DOCS] Add example for runApiTest browser_step type
