DataDog/terraform-provider-datadog

- website/docs/r/downtime.html.markdown
this PR adds previously undocumented attributes `active` and `disabled` to the downtime resource documentation
> docs: add undocumented attributes to downtime resource

- datadog/provider.go
- datadog/resource_datadog_metric_metadata.go
- datadog/resource_datadog_metric_metadata_test.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/datadog-accessors.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/metric_metadata.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/series.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/snapshot.go
- vendor/vendor.json
- website/docs/r/metric_metadata.html.markdown
- Adds a resource for [metric metadata](https://docs.datadoghq.com/api/#metrics-metadata-update).
- This would allow you to edit metric metadata, for instance, adding a description for a metric to let other people know what the metric means and its values should be, or to set the unit of a metric, and so on.
- Metric metadata are read and update only, they're created automatically when you send a metric to DD.
- [My PR for go-datadog-api dep adding support for metric metadata](https://github.com/zorkian/go-datadog-api/pull/109).
> Add metric metadata

- datadog/resource_datadog_timeboard.go
- vendor/github.com/kr/pretty/License
- vendor/github.com/kr/pretty/Readme
- vendor/github.com/kr/pretty/diff.go
- vendor/github.com/kr/pretty/formatter.go
- vendor/github.com/kr/pretty/pretty.go
- vendor/github.com/kr/pretty/zero.go
- vendor/github.com/kr/text/License
- vendor/github.com/kr/text/Readme
- vendor/github.com/kr/text/doc.go
- vendor/github.com/kr/text/indent.go
- vendor/github.com/kr/text/wrap.go
- vendor/vendor.json
* Addresses #20 and #19
* Most calls to `schema.ResourceData.Set` failed to check returned error, surpressing actual errors
* Zorkian's `go-datadog-api.v2` uses accessor methods and not all the provider code was updated
* Switched to using kr/pretty logging to dump objects during debug
* Changed events, groups, and scopes from `schema.TypeSet` to `schema.TypeList`, there were errors that were resolved by moving to `TypeList`. I don't know if this was the right path, maybe we could revisit making these sets in the future. Errors were like this:
```
* module.datadog_timeboard.my_timeboard: datadog_timeboard.my_timeboard: Invalid address to set: []string{"graph", "2", "scope"}
```
> Using accessors, adding err checks

- datadog/import_datadog_monitor_test.go
- datadog/resource_datadog_monitor.go
- datadog/resource_datadog_monitor_test.go
- website/docs/r/monitor.html.markdown
Recovery thresholds are a recently-added datadog feature:
https://www.datadoghq.com/blog/introducing-recovery-thresholds/
This commit adds support for warning_recovery and critical_recovery
threshold configurations. Resolves issue #33 
I also changed the tests from `metric alert` to `query alert` because Datadog automatically reclassifies these more complex monitors, see issue #3
> Add support for monitor recovery thresholds.

- website/docs/r/monitor.html.markdown
Single quotes are not valid Terraform syntax.
> Fix quoting in documentation

- datadog/resource_datadog_downtime.go
- datadog/resource_datadog_downtime_test.go
- website/docs/r/downtime.html.markdown
This PR is a shot at trying to implement the `monitor_id` field for downtime.
Since this is my first PR for terraform, please let me know if there are any hard mistakes, and I'll more than happy to work through them.
> Implement monitor_id support for downtime

- website/docs/r/monitor.html.markdown
The PR fix a mismatch between the code, where the default value for datadog_monitor.notify_no_data [is false](https://github.com/terraform-providers/terraform-provider-datadog/blob/master/datadog/resource_datadog_monitor.go#L97) and the documentation.
> Fix mismatch between code and documentation

- datadog/resource_datadog_metric_metadata_test.go
- datadog/resource_datadog_monitor_test.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/README.md
- vendor/gopkg.in/zorkian/go-datadog-api.v2/client.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/comments.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/dashboard_lists.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/datadog-accessors.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/integrations.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/monitors.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/request.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/series.go
- vendor/gopkg.in/zorkian/go-datadog-api.v2/users.go
- vendor/vendor.json
* Updated DataDog Client (`go-datadog-api.v2`) to version `v2.10.0`, which includeds this fix from release `v2.8.1`:
```
Monitor tags weren't being removed when the list of tags was empty
```
* Added test for removing an existing monitors tags and re-running a `terraform apply`
* This closes issue #43
> Client to v2.10.0 + Bugfix for monitor tag removal on update

- datadog/resource_datadog_user.go
The endpoint to handle resources of type `User` doesn't accept anymore the `role` parameter, that is now ignored.
This is currently a problem because beside not being able to set a User role, Terraform remains in a dirty state where `terraform plan` always wants to update `role`.
See https://github.com/terraform-providers/terraform-provider-datadog/issues/12 for one of the issues we're facing.
> Deprecated role for user resource

- website/docs/r/monitor.html.markdown
- website/docs/r/timeboard.html.markdown
- website/docs/r/user.html.markdown
This is an attempt to improve docs as a way to mitigate a few recurring issues. In some cases, a better documentation is the only workaround we can provide in the short term to mitigate known pain points.
> Improve documentation

- datadog/resource_datadog_user.go
We already deprecated the use of the `role` attribute because the Datadog API just ignore the corresponding parameter.
The problem persists because if you manually add an user role through the UI, `terraform plan` will always try to set it to an empty string (the default value).
This PR makes Terraform completely unaware of the `role` API param, so it won't try to even read it from the response payload.
> Finish deprecating `role` argument for User resource

- website/docs/r/timeboard.html.markdown
The existing timeboard docs say that "type" should be "line", "bar", or
"area". Datadog expects this to be "bars", not "bar". This commit
corrects the documentation from "bar" to "bars".
> Fix typo in timeboard documentation

- website/docs/r/monitor.html.markdown
As noted in the [Datadog API docs](https://docs.datadoghq.com/api/?lang=python#create-a-monitor).
> docs: monitor type

- datadog/resource_datadog_user.go
In order to introduce `access_role`, `is_admin` has to be deprecated, then removed. This is the first step.
See #4 for more details.
> Deprecate is_admin for resource "datadog_user"

- datadog/provider.go
- datadog/resource_datadog_screenboard.go
- datadog/resource_datadog_screenboard_test.go
- vendor/github.com/zorkian/go-datadog-api/dashboards.go
- vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
- vendor/github.com/zorkian/go-datadog-api/monitors.go
- vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
- vendor/github.com/zorkian/go-datadog-api/screenboards.go
- vendor/vendor.json
- website/datadog.erb
- website/docs/r/screenboard.html.markdown
This PR adds full support for Datadog screenboards.
All 19 widgets are supported.
Solves #52.
@masci I suppose you should be the one reviewing this?
> Add datadog_screenboard resource

- website/docs/r/user.html.markdown
> Mention is_admin is deprecated in the docs

- datadog/resource_datadog_monitor.go
Stops using the [`GetOk`](https://godoc.org/github.com/hashicorp/terraform/helper/schema#ResourceData.GetOk) method when updating the monitor struct for the `new_host_delay` parameter. 
The GetOk method does a check both to see if the key is specified in the schema configuration AND is **not** the golang zero value for that type. So Using the GetOk function, specifying a `new_host_delay: 0` would actually cause the default to be used.
It seems like GetOk shouldn't be used for an int type that has a default value if `0` is an allowed value for that key. 
Get-ing the key (the change introduced in this PR), you can specify a 0 value to mean `0` or specify no value to fallback to the default. 
Alternatively, we could use the `GetOkExists` function, but that is only available starting with …
> Allow new_host_delay to be unset

- datadog/provider.go
- datadog/resource_datadog_integration_gcp.go
- datadog/resource_datadog_integration_gcp_test.go
- datadog/resource_datadog_timeboard.go
- vendor/github.com/zorkian/go-datadog-api/dashboards.go
- vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
- vendor/github.com/zorkian/go-datadog-api/integrations.go
- vendor/github.com/zorkian/go-datadog-api/monitors.go
- vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
- vendor/github.com/zorkian/go-datadog-api/series.go
- vendor/vendor.json
- website/datadog.erb
- website/docs/r/integration_gcp.html.markdown
This pull request is for #107 , adds Google Cloud Platform integration.
> Add Google Cloud Platform integration

- website/docs/r/monitor.html.markdown
Specifying that the evaluation_delay option can only be used with metric alerts. Host monitors, for example, don't have that option.
> Adding info on evaluation_delay option

- datadog/resource_datadog_timeboard.go
- website/docs/r/timeboard.html.markdown
Hi there!
This PR adds support for `node_type`, `fill_min` and `fill_max` options as well as fixing hostmap widget setting. These were recently added to the timeboard structures of `zorkian/go-datadog-api` via https://github.com/zorkian/go-datadog-api/pull/173 and https://github.com/zorkian/go-datadog-api/pull/178.
> Add new hostmap widget options (node type, fill_min and fill_max).

- datadog/resource_datadog_timeboard.go
- datadog/resource_datadog_timeboard_test.go
Fixes https://github.com/terraform-providers/terraform-provider-datadog/issues/29
`palette_flip` is part of the `style` map but it's the only item of type boolean (all other items are strings), so the only way to make it work is to treat it as a string as well. Let's suppress the diff when the only difference between what's reported by the API and the state is the format (`true` vs `1`).
In the same PR a small fix to avoid setting the zero value for `precision` when the field is indeed missing from the resource definition.
> Fix diff for `palette_flip`

- CHANGELOG.md
- datadog/resource_datadog_screenboard.go
- datadog/resource_datadog_timeboard.go
- datadog/resource_datadog_timeboard_test.go
- vendor/github.com/zorkian/go-datadog-api/dashboards.go
- vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
- vendor/github.com/zorkian/go-datadog-api/monitors.go
- vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
- vendor/github.com/zorkian/go-datadog-api/screenboards.go
- vendor/vendor.json
Bump the datadog API dep to 2.18.0 and add support for `includeZero` and `includeUnits`.
I want units and zeros on my axes! :smiley_cat: 
The bump also [changed Screenboard's width and height](https://github.com/zorkian/go-datadog-api/pull/190) so there is perhaps some trouble with the use of strings here. #118 implied this wasn't an ok change to make?
This also fixes #119 
Thanks for your consideration!
> Bump datadog api to v2.18.0 and add support for include units and zero

- datadog/resource_datadog_timeboard.go
- datadog/resource_datadog_timeboard_test.go
- vendor/github.com/zorkian/go-datadog-api/dashboards.go
- vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
- vendor/github.com/zorkian/go-datadog-api/helpers.go
- vendor/github.com/zorkian/go-datadog-api/monitors.go
- vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
- vendor/vendor.json
Updated `go-datadog-api` to `master` in order to include https://github.com/zorkian/go-datadog-api/pull/194 and partially address #117 (one fix is still missing, see https://github.com/zorkian/go-datadog-api/pull/195):
```
govendor fetch github.com/zorkian/go-datadog-api/...@1df5bda80d16ccfa8e99c543dbeb731665acbfca
```
Also fixed a bug introduced in #121, now `include_units` and `include_zero` are fully supported.
> bump client to latest, fix precision and yaxis.include_* fields

- datadog/resource_datadog_screenboard.go
- datadog/resource_datadog_screenboard_test.go
Waiting for https://github.com/zorkian/go-datadog-api/pull/195 to be merged, normalize height and width to strings using `PrecisionT` type from `go-datadog-api`. Fixes acceptance tests.
Most of the changes to `datadog/resource_datadog_screenboard_test.go` are about indenting HCL code in the fixtures.
> Make screenboard's width and height accept strings and numbers

- vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
- vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
- vendor/vendor.json
Update the `go-datadog-api` to include https://github.com/zorkian/go-datadog-api/pull/202. 
```
govendor fetch github.com/zorkian/go-datadog-api/...@66f4fd4202d9d3e543608051a91a09eebc870966
```
Aims to fix the `cannot unmarshal number into Go struct field TileDefStyle.fillMax of type string ` when using decimal numbers in `FillMin` and/or `FillMax`
> Bump go client to include type fix in widget struct

- datadog/resource_datadog_downtime.go
This PR fixes the order for reading the start dates and end dates for downtimes.
Currently, if you use `start_date` or `end_date` in your configuration file, you can create the initial downtime OK. However, when you run terraform apply, Terraform will notice that the state is different than whats in the config and attempt to update it. However, since the build downtime struct saw that the `start` field was in the state, it used that instead of the user provided start_date. This makes sure we take precedence of the start_date field. 
If the user specifies the `start` and `end` this functionality will still work as expected.
> Fix order for reading start times on downtime

- website/datadog.erb
Since it was missing from https://www.terraform.io/docs/providers/datadog/index.html.
> Add missing AWS integration link

- CHANGELOG.md
Get ready for 1.7.0 release by manually updating the Changelog
Used the diff here to determine what I should have included - https://github.com/terraform-providers/terraform-provider-datadog/compare/v1.6.0...master
> Update changelog for 1.7

- datadog/provider.go
This makes debugging for developers & users of this provider easier by exposing all requests & responses in the log (when >`DEBUG` severity is set).
Example:
```
---[ REQUEST ]---------------------------------------
GET /api/v1/validate?api_key=<redacted>&application_key=<redacted> HTTP/1.1
Host: app.datadoghq.com
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip
-----------------------------------------------------
2019/02/22 17:48:23 [DEBUG] Datadog API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Content-Length: 14
Cache-Control: no-cache
Content-Type: application/json
Date: Fri, 22 Feb 2019 17:48:23 GMT
Dd-Pool: dogweb_sameorig
Pragma: no-cache
Set-Cookie: DD-PSHARD=142; Max-Age=604800; Path=/; expires=Fri, 01-Mar-2019 17:48:23 GMT; …
```
> provider: Enable request/response logging

- datadog/resource_datadog_user.go
- datadog/resource_datadog_user_test.go
Datadog now can add 'access_role'  property when create Datadog users, but Terraform was not supported 'access_role' property. #4 is request of that so I added this function.
> Add access_role to resource_datadog_user

- datadog/provider.go
- datadog/resource_datadog_synthetics_test_.go
- datadog/resource_datadog_synthetics_test_test.go
- go.mod
- go.sum
- vendor/github.com/hashicorp/terraform/helper/resource/testing.go
- vendor/github.com/zorkian/go-datadog-api/README.md
- vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
- vendor/github.com/zorkian/go-datadog-api/events.go
- vendor/github.com/zorkian/go-datadog-api/helpers.go
- vendor/github.com/zorkian/go-datadog-api/monitors.go
- vendor/github.com/zorkian/go-datadog-api/synthetics.go
- vendor/modules.txt
- website/docs/r/synthetics.html.markdown
This PR will add support for CRUD operations on API Synthetics Tests.
We need to wait for [this PR](https://github.com/zorkian/go-datadog-api/pull/228) to be merged before merging this one.
Either run `make testacc` to run acceptance tests or try the CLI tool:
```sh
make build
cp ~/go/bin/terraform-provider-datadog ~/.terraform.d/plugins/
terraform init
terraform apply
```
With a basic `main.tf` terraform config file:
```tf
provider "datadog" {
api_key = "XXX"
app_key = "XXX"
}
resource "datadog_synthetics_test" "foo" {
type = "api"
request {
method = "GET"
url = "https://docs.datadoghq.com"
}
assertions = [
{
type = "statusCode"
operator = "is"
target = "200"
},
{
type = "responseTime"
operator = "lessThan"
target = "2000"
}
]
locations = [ "aws:eu-central-1", "aws:ap-northeast-1" ] …
```
> Support Synthetics Tests

- website/datadog.erb
Re-order the links by alphabetical order (like eg. AWS does), and add the link to the datadog_synthetics docs page.
> Re-order doc links, and add synthetics link

- CHANGELOG.md
- website/datadog.erb
We were missing the documentation link for the new synthetics resource. 
Essentially merges this PR into the `stable-website` branch - https://github.com/terraform-providers/terraform-provider-datadog/pull/174
> Update the stable-website with whats on master

- website/docs/r/synthetics.html.markdown
Adding documentation for an optional request body to the synthetics terraform. 
https://github.com/terraform-providers/terraform-provider-datadog/blob/master/datadog/resource_datadog_synthetics_test_.go#L94
> Add request body to synthetics documentation

- website/docs/r/monitor.html.markdown
This documents the limitation of key interpolation that was hit in #159 and suggests a working solution for the usecase. I don't see a better way to solve this, as it is an HCL limitation (so something that should get interpolated even before it gets passed to the provider).
> Document HCL limitation of key interpolation. Fixes #159

- website/docs/r/user.html.markdown
* Adding documentation about access_role which was merged in https://github.com/terraform-providers/terraform-provider-datadog/pull/155.
* Additional warning about is_admin
> Document access_role in favour of is_admin.

- datadog/resource_datadog_monitor.go
- datadog/resource_datadog_monitor_test.go
- website/docs/r/monitor.html.markdown
This may need more testing 😬 
Goal is to expose the `enable_logs_sample` option for log alert monitors which corresponds to the checkbox on the UI to enable capturing log samples that triggered the alert.
Related issue: https://github.com/terraform-providers/terraform-provider-datadog/issues/139
> Add support for enable_logs_sample option in log monitors

- website/docs/r/metric_metadata.html.markdown
- This was the only example that wasn't `terraform fmt`ed so here's a
fix. :-)
> Make the `metric_metadata` docs example adhere to `terraform fmt`

- datadog/resource_datadog_downtime.go
- datadog/resource_datadog_downtime_test.go
- go.mod
- go.sum
- vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
Add monitor tags to the downtime resource to address https://github.com/terraform-providers/terraform-provider-datadog/issues/162.
My first real foray into go and terraform, so let me know if I did anything wrong. Mostly copied a bunch of stuff.
The tests pass locally, but I refrained from running the acceptance tests locally because of the note mentioning that it costs money to run them. I'm hoping CI will catch any issues there.
However, things are gonna fail until https://github.com/zorkian/go-datadog-api/pull/227 gets merged in.
> Add monitor_tags getting and setting to downtime resource

- CHANGELOG.md
- go.sum
This PR contains two commits that I wanted to do before 1.9.0 release:
* tidy up the `go.sum` file (I just ran `go mod tidy`)
* update of `CHANGELOG.md`
> Changelog and tidy

- datadog/import_datadog_downtime_test.go
- datadog/resource_datadog_downtime_test.go
- datadog/resource_datadog_monitor.go
- datadog/resource_datadog_monitor_test.go
- datadog/resource_datadog_user.go
- datadog/resource_datadog_user_test.go
- go.mod
- go.sum
- vendor/github.com/zorkian/go-datadog-api/Makefile
- vendor/github.com/zorkian/go-datadog-api/monitors.go
- vendor/modules.txt
This PR fixes various minor issues in the acceptance test suite. Some of these were only tests forgotten to be updated, but some were real issues, one of which also required a fix in go-datadog-api (thus the dependency update).
> Fix various acceptance tests failures

- datadog/resource_datadog_monitor.go
Anomaly monitors allow for setting a "trigger_window" and "recovery_window" within a "threshold_windows" map, as mentioned in https://github.com/terraform-providers/terraform-provider-datadog/issues/73. This PR adds support for managing those values via Terraform.
> Adds ThresholdWindows

- website/docs/r/monitor.html.markdown
I wanted to add this in #191 but totally forgot about it, so adding it now.
> Add documentation for datadog_monitor's threshold_windows

- datadog/resource_datadog_screenboard.go
The element type is set to `schema.TypeInt`, which does not allow us to
do interpolation. By changing this type to string all seem to work
correctly.
Our terraform configuration
```
monitor {
id = "${module.poller_latency.id}"
}
```
The error we are seeing is this:
```
widget.0.monitor (id): cannot parse '' as int: strconv.ParseInt: parsing "${module.poller_latency.id}": invalid syntax
```
Feel free to close this PR if this is a not relevant / breaking change, i could be missing context here.
> Change monitor element schema to TypeString

- datadog/resource_datadog_monitor.go
Fix log monitor UI issue of the search query
-  generate queryConfig.queryString from the query attribute
> #148 Fix log monitor UI issue: generate queryConfig.queryString from query

- datadog/resource_datadog_monitor.go
Without this, having a monitor that's not of type `log alert` would result in not saving computed value for `query_config` on creation and thus having non-empty plan after first apply.
> Make sure the computed value for monitor's query_config gets stored on creation

- website/docs/r/monitor.html.markdown
The docs for `include_tags` seem to have been incomplete, so I grabbed the same wording from the [api docs](https://docs.datadoghq.com/api/?lang=python#get-a-monitor-downtime) to clarify usage.
> docs(monitor): finish sentence for include_tags

- datadog/resource_datadog_screenboard.go
- datadog/resource_datadog_screenboard_test.go
- go.mod
- go.sum
- vendor/github.com/zorkian/go-datadog-api/dashboards.go
- vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
- vendor/github.com/zorkian/go-datadog-api/downtimes.go
- vendor/github.com/zorkian/go-datadog-api/screen_widgets.go
- vendor/modules.txt
In the documentation it is mentioned that `custom_bg` is supported for a screenboard (https://www.terraform.io/docs/providers/datadog/r/screenboard.html#palette-2). 
But no `custom_bg_color` field is available such as https://www.terraform.io/docs/providers/datadog/r/timeboard.html#custom_bg_color.
I added the field to the screenboard code.
> Add custum_bg_color to screenboard

- website/docs/r/monitor.html.markdown
Add a link to the Datadog Documentation in the monitor terraform docs that provides the mapping between API/Terraform monitor `types` and the ones that you see in the Datadog platform. 
Help make choosing a monitor type easier!
> Add link to documentation about monitor types

- datadog/resource_datadog_monitor.go
- datadog/resource_datadog_monitor_test.go
Fixes #182 as monitor tags order has no meaning and are not guaranteed to be in the same order
> Fixes #182 - Monitor Tags are not sorted

- datadog/resource_datadog_monitor.go
- website/docs/r/monitor.html.markdown
Adds a default of 10 minutes for the no_data_timeframe to be used instead of the 0 value the provider currently emits. 
Ultimately looks to fix #206
> Add default of 10m for monitor no data timeframe

- datadog/resource_datadog_screenboard.go
- datadog/resource_datadog_screenboard_test.go
- datadog/resource_datadog_timeboard.go
- datadog/resource_datadog_timeboard_test.go
- website/docs/r/screenboard.html.markdown
- website/docs/r/timeboard.html.markdown
> Allow adding metadata aliases for widgets in screenboards and timeboards

- datadog/resource_datadog_downtime.go
- website/docs/r/downtime.html.markdown
1. Adds the timezone parameter
1. Adds descriptions to parameters
1. Adds validation to monitor_tags
1. Ensures that the updated downtime id is correctly handled for future immutable downtimes
> Downtime improvements

- website/datadog.erb
- website/docs/r/examples/monitors.html.markdown
A quick POC to adding an `examples` section to the Provider website docs. The idea being that we could do this for each complex resource we have where the number of examples needed wouldn't really fit on the resource page directly.
> Add examples section to docs

- CHANGELOG.md
- datadog/resource_datadog_monitor_test.go
- datadog/resource_datadog_synthetics_test_.go
- datadog/resource_datadog_synthetics_test_test.go
- go.mod
- go.sum
- vendor/github.com/zorkian/go-datadog-api/datadog-accessors.go
- vendor/github.com/zorkian/go-datadog-api/synthetics.go
- vendor/modules.txt
- website/docs/r/monitor.html.markdown
**Please do not merge this PR until the [PR on go-datadog-api](https://github.com/zorkian/go-datadog-api/pull/243) is merged**.
> Support Synthetics tests in composite monitors

- datadog/resource_datadog_timeboard.go
Suppress the diff on the precision attribute of timeboard graphs when it makes sense. 
Some widget types allow the `precision` field to be set. The default value for this is `2`. If the value isn't set in the config, the Datadog API applies a value of `2` on certain widget types (mainly query value widgets)
Since the state has a `2` returned by the API, it doesn't match the config value of `""`, causing a diff. We could provide this as a default to the schema, but its not a valid attribute to all graph widgets, so its cleaner to suppress the diff in this case.
> Suppress diff on default precision

- datadog/resource_datadog_timeboard.go
- website/docs/r/timeboard.html.markdown
This makes sure that `extra_col` is checked for proper value and only used for `change` visualization. Related to #142.
> Timeboard extra_col fix

- datadog/resource_datadog_monitor.go
- datadog/resource_datadog_monitor_test.go
- website/docs/r/monitor.html.markdown
This PR looks to accomplish a few things surrounding the `silence` attribute of monitor resources. 
* Add a deprecation notice that we'll stop supporting the `silenced` param soon. (In a couple Major versions of the Provider as outlined by the best practices doc - https://www.terraform.io/docs/extend/best-practices/deprecations.html)
* Add the ability to specify a `-1` on any scope of the silenced attribute to unmute that scope. This will make a separate API call to unmute those scopes (Only on updates, newly created monitors shouldn't be muted :) ) 
* Fix an issue where running terraform apply would detect a diff on the silence scope if the timestamp were in the past. This is due to the Datadog Monitor API not returning scopes with timestamps in the past in the API response. So the …
> Deprecate Silence attribute and Fix multiple terraform runs

- datadog/import_datadog_downtime_test.go
- datadog/resource_datadog_downtime.go
- datadog/resource_datadog_monitor.go
- datadog/resource_datadog_monitor_test.go
* Set datadog_downtime.timezone attribute in resourceDatadogDowntimeRead,
handle it in import test
* Make datadog_downtime.tags a TypeSet to be able to properly ignore
differences in ordering of its contents
* Fix two regressions caused by calling resourceDatadogMonitorRead from
resourceDatadogMonitorUpdate and resourceDatadogMonitorCreate:
* Make sure that API sometimes changing "metric alert" to "query alert"
continues to be ignored
* Fix tests for threshold values to always expect floats
The last change should be mentioned in the changelog, because that will actually create a non-empty plan for people who have used integers as values for thresholds previously - with next apply, these are all going to change to floats (one-time only). It's not really a regression, since the values will …
> Fix several integration tests and related code

- website/docs/r/synthetics.html.markdown
All of the parameters are in seconds: https://docs.datadoghq.com/api/?lang=python#create-a-test.
There can be some confusion because some datadog docs say its in
minutes e.g. in https://docs.datadoghq.com/synthetics/api_tests/?tab=httptest#alert-conditions
it is mentioned:
```
At least one location was in failure (at least one assertion failed) during the last X minutes,
```
Also, one of the parameters is called `min_failure_duration`,
which caused some confusion whether the `min` referred to
minimum or minutes : ).
Specify the units explicilty, and save others from being confused
like we were.
> Mention units explicitly

- datadog/resource_datadog_monitor.go
To change a monitor type, one needs to actually delete the old one and create new, which is precisely what `ForceNew` does.
> Mark datadog_monitor.type as ForceNew, since changing type is not actually possible

- datadog/resource_datadog_integration_gcp_test.go
- datadog/resource_datadog_user_test.go
Fixes up the last two integration tests as of this writing:
TestAccDatadogIntegrationGCP and TestAccDatadogUser_Updated
Neither of these tests were inherently broken, just needed some coercion to play nicely with the CI
GCP: 
The project drifted a bit from the CI but is difficult to fix with limited access. This should address that for now while working on a longer term solution
User:
A user may only edit their own email via the API, not someone elses. The CI DD account likely has a `test@` user in the org. However this doesn't play nicely with running the integration tests locally. This uses a random user email so we get the same test behavior both on the CI and locally.
> Fix up the GCP and User tests

- datadog/resource_datadog_monitor.go
Fixes #241 
The API will return `query alert` or `metric alert` depending on the query. We currently ignore the fact that the user may have a `metric alert` but the API returns a `query alert` but we don't ignore the opposite. 
This config seems to replicate the behavior:
```
name = "Anomolous CPU usage"
type = "query alert"
message = "CPU utilization is outside normal bounds"
query = "avg(last_4h):anomalies(ewma_20(avg:system.cpu.system{env:prod,service:website}.as_rate()), 'robust', 3, direction='below', alert_window='last_30m', interval=60, count_default_zero='true', seasonality='weekly') >= 1"
thresholds {
critical          = 1.0
critical_recovery = 0.0
}
threshold_windows {
trigger_window    = "last_30m"
recovery_window   = "last_30m"
}
notify_no_data    = false
renotify_interval = …
```
> `datadog_monitor` ignore `query alert` vs `metric alert` diff

- datadog/resource_datadog_monitor.go
Even though this works exactly the same, it's somewhat clearer.
> Clarify the logic around monitors changing types by adding parentheses

- datadog/resource_datadog_monitor.go
This PR takes us back to using the `suppressDiff` function for the case of monitor types being one of `metric alert` or `query alert`
The issue with the previous approach was that the diff is calculated based on what the state is refreshed as vs what the config has. Take this example:
User provides `metric alert` in the config. Runs terraform apply and the API successfully creates the monitor (but the monitor is really a `query alert`. Future API calls return `query alert` in the response. 
With older monitors (created before Provider 2.0.0), the state contained `query alert` because the diffsuppress ignored the diff and set the state to contain what the API returned. 
With 2.0.0 and 2.0.1, since this suppression was moved into the Read function, the state wasn't updated with the api …
> Use suppressdiff on monitor type

- datadog/resource_datadog_user.go
The `is_admin` flag that is going through its deprecation process has a lower precedence than the `access_role` flag. 
The is_admin doesn't really get used in the request, but is still returned with a different value depending on what the access_role for that user is set to. For this reason we should make it a Computed value to avoid spurious diffs while users make the transition. 
Before this change, if you were using the is_admin config option and had it set to True, you'd get a user that was an admin. If you transition to the access_role flag, and remove the `is_admin`, the default was False, and Terraform would attempt to mark this flag as false. Since the `access_role` takes precedence this led to an untrue diff being shown to the user on each new plan/apply. This removes that diff …
> Make is_admin computed

- website/docs/r/monitor.html.markdown
Clarify that the trigger_window and recovery_winow options are required for anomaly monitors.
> Clarify threshold windows are required for anomaly monitors

- datadog/resource_datadog_integration_aws.go
Fixes #132.
As confirmed by DD's team responsible for this part of API, operations on AWS integration on a single account should be serialized.
> Add a mutex to all AWS integration operations that change data to prevent race conditions

- datadog/provider.go
A `false` response from the Validation command could mean either that the credentials are missing or expired. This updates the error wording a bit to make that clearer.
> Update error wording for credential validation

- datadog/resource_datadog_monitor.go
- datadog/resource_datadog_monitor_test.go
This fixes issue #259
The `threshold_windows` should be added only if a window has been set
The Options structure already has the flag to omit it when it is empty:
```
type Options struct {
...
EscalationMessage *string           `json:"escalation_message,omitempty"`
Thresholds        *ThresholdCount   `json:"thresholds,omitempty"`
ThresholdWindows  *ThresholdWindows `json:"threshold_windows,omitempty"`
IncludeTags       *bool             `json:"include_tags,omitempty"`
...
}
```
> Correction to the threshold_windows

- datadog/resource_datadog_downtime.go
- datadog/resource_datadog_downtime_test.go
- website/docs/r/downtime.html.markdown
This PR includes 2 fixes:
* On updates to downtime attributes, `start` and `end` are no longer sent when unchanged. This makes it possible to update various downtime attributes without having to touch the timestamps.
* Fixes non-empty plan for monitors that have empty `monitor_tags`.
* Note that this issue wasn't previously discovered because of a faulty test (that I fixed in the same commit). The test is faulty because it seems `ConflictsWith` doesn't work right when one of the attributes has its content from a variable - this seems to be a bug in Terraform and I'm currently discussing that with Hashicorp folks.
> Downtime fixes

- datadog/resource_datadog_synthetics_test_.go
- datadog/resource_datadog_synthetics_test_test.go
Considering:
- TF nested schemas is limited to string values
- `follow_redirects` is a boolean in Datadog json api
we need to convert boolean like this:
- true => "true"
- false => "false"
☝️better because `follow_redirects` is advertised as a boolean in the documentation
> [Synthetics] Fix follow redirects

- website/docs/r/dashboard.html.markdown
- website/docs/r/screenboard.html.markdown
Correct typo on the `no_metric_groups` and `no_host_groups` options in the dashboard documentation. 
The schema (and the example config) has these as plurals, but the description had them as singular. The proper version is the plural - https://github.com/terraform-providers/terraform-provider-datadog/blob/ee1f7cfb0dae3e59cc2d685ed2b1f3a830f43d59/datadog/resource_datadog_dashboard.go#L1918
Fixes #284
> Correct typo on dashboard options

- datadog/resource_datadog_synthetics_test_.go
- datadog/resource_datadog_synthetics_test_test.go
- website/docs/r/synthetics.html.markdown
- Add support for ssl tests
- Add acceptance test
- Update doc
- Have subtype defaults to http for api tests
- Make sure existing TF files won't diff
> [Synthetics] Support SSL

- datadog/resource_datadog_dashboard.go
- website/docs/r/dashboard.html.markdown
- Add a safe type assert for all optional fields in the dashboard resource (includes `sort->facet` and `compute->interval`). 
- Update documentation
> [dashboards] Safely type assert optional fields from log and apm query

- datadog/resource_datadog_dashboard.go
- This PR fixes panic crashes that occur when we don't set some required fields
Since `TypeMap` doesn't seem to let us use standard schema functions for its sub elements (e.g. `Required`, `Validate`, `DiffSuppressFunc`), we decided to type assert required fields also (i.e. `compute->aggregation`, `sort`->`aggregation` and `sort`->`order` fields). So, if they aren't present, they aren't sent to the API and this will result in a response error.
> [dashboards] Add safe type asserts to required fields

- GNUmakefile
Adds a new make command `update-go-client`. 
By default this will update the go client to the latest master. 
It also accepts an argument `GO_CLIENT_VERSION` so you can pick the revision you want to update to, ex:
```
make update-go-client GO_CLIENT_VERSION=v2.22.0
```
> Add make command to update go api client dep

- datadog/resource_datadog_integration_pagerduty.go
- datadog/resource_datadog_integration_pagerduty_service_object_test.go
- datadog/resource_datadog_integration_pagerduty_test.go
- website/docs/r/integration_pagerduty.html.markdown
Previously, doing any update on the PD resource would delete the individual service objects. This PR fixes that (at the cost of doing the migration from inline services to individual service objects somewhat harder, but that's a one-time migration process, so shouldn't hurt a lot - I don't see a better way to solve this).
Fixes #299.
> Make sure PD services don't get removed by updating PD resource

- datadog/resource_datadog_dashboard_test.go
- datadog/resource_datadog_screenboard_test.go
- datadog/resource_datadog_service_level_objective_test.go
- datadog/resource_datadog_timeboard_test.go
Looks like nobody ran these for a while and some failures accumulated due to several changes, so here's the fix to make all tests pass again (also on TF 0.12)
> Fix integration tests (again)

- datadog/resource_datadog_integration_pagerduty.go
- datadog/resource_datadog_integration_pagerduty_service_object.go
Without this, people would experience TF error out if the integration was manually deactivated outside TF (the Read functions would fail with 404 and TF wouldn't recover from that).
> Add missing 'exists' methods to PD integration and PD service objects

- datadog/resource_datadog_dashboard.go
- datadog/resource_datadog_dashboard_test.go
- website/docs/r/dashboard.html.markdown
`show_legend` was in the timeseries schema but not being added to the state/api request. This addresses that. 
Fixes: #323
> Properly add show_legend

- website/docs/r/synthetics.html.markdown
> Fix synth resource docs to reference `id` as exported attribute

- datadog/resource_datadog_logs_index.go
- website/docs/r/logs_index.html.markdown
There are existing indexes without exclusion filter. we need to allow optional in order to import them.
> Update requirements for exclusive filter

- website/docs/r/downtime.html.markdown
Motiviation:
- the existing documentation provides only one example for the Downtime resource
- the existing documentation provides an example that mutes **all** monitors
- Muting all monitors is not necessarily the best thing to do for large enterprises
- this PR is an attempt to show developers how to configure a Downtime for a single monitor
> add example to the Downtime resource documentation

- website/docs/r/dashboard.html.markdown
Add note in the docs that the `Manage Status` widget is also known as the `Monitor Summary` widget. This widget goes by both names in the documentation page - https://docs.datadoghq.com/graphing/widgets/monitor_summary/
Fixes - #340 and thanks @generalpiston
> Add note about monitor summary widget

- README.md
Make an explicit note that forks should still live under the $GOPATH/src/github.com/terraform-providers/terraform-provider-datadog` folder to be able to run/build/test this project successfully.
> Add note about contributing from forks

- CHANGELOG.md
- datadog/resource_datadog_service_level_objective.go
- website/docs/r/service_level_objective.html.markdown
removing `monitor_search` flag while unsupported
> monitor_search is not yet supported

- datadog/resource_datadog_monitor.go
This PR will resolve https://github.com/terraform-providers/terraform-provider-datadog/issues/383.
Datadog seems to have changed the response of monitors recently modified and the response no longer includes "no_data_timeframe" if "notify_no_data" is false.
For example, if I execute the following script:
```sh
for monitor_id in $OLD_MONITOR_ID $RECENTLY_MODIFIED_MONITOR_ID; do
curl -s -X GET \
-H "DD-API-KEY: ${DATADOG_API_KEY}" \
-H "DD-APPLICATION-KEY: ${DATADOG_APP_KEY}" \
-d "group_states=all" \
"https://api.datadoghq.com/api/v1/monitor/${monitor_id}" | \
jq '{modified, options: .options | {notify_no_data, no_data_timeframe}}'
done
```
The output is like below:
```
{
"modified": "2019-09-17T08:08:32.094503+00:00",
"options": {
"notify_no_data": false,
"no_data_timeframe": 10
}
}
{ …
```
> Ignore the change of no_data_timeframe if notify_no_data is false

- datadog/resource_datadog_screenboard.go
This fixes https://github.com/terraform-providers/terraform-provider-datadog/issues/105#issuecomment-581938484
> Properly set screenboard attributes from client response to not produce non-empty plans

- datadog/resource_datadog_dashboard.go
- datadog/resource_datadog_screenboard.go
- website/docs/r/dashboard.html.markdown
- website/docs/r/screenboard.html.markdown
Remove the count and start monitor summary widget params from the docs and deprecate them.
While these params are still supported (and will continue to be), they don't appear to be used by anyone and we don't know of any use cases for them, so we should remove them from the docs to avoid confusion.
Related: https://github.com/terraform-providers/terraform-provider-datadog/pull/300 (the `sort` param does have use cases so we're adding it to the docs here: https://github.com/DataDog/documentation/pull/6568).
> Hide deprecated monitor summary widget params

- datadog/resource_datadog_downtime.go
Fixes #315 - if the downtime gets deleted (==canceled) manually in UI, we have to consider it canceled and recreate it.
> Gracefully handle downtimes that were canceled manually

- datadog/resource_datadog_service_level_objective.go
- datadog/resource_datadog_service_level_objective_test.go
Optional fields in the threshold object were always added to the update payload, even when they were not actually set in the state or the configuration.
This broke the update function as the `warning` field cannot be set to a lower value that the slo value (`target`), which triggers a `warning must be greater than slo value` error.
If the warning field was not set, the `ResourceData.Get()` function would return the default value for the field, which is `0.0` for a float, hence the error being triggered.
This PR fixes this problem by using the `ResourceData.GetOk()` to check if the field was actually set or not.
The code was compiled and tested for two scenarios, both working as expected:
- The update of an slo created with the previous terraform provider
- The creation and then the update …
> Fix optional threshold fields handling in update function

- datadog/resource_datadog_dashboard.go
- datadog/resource_datadog_dashboard_test.go
- website/docs/r/dashboard.html.markdown
~This is a bit premature as https://github.com/zorkian/go-datadog-api/pull/296 is still awaiting review, but I've confirmed it works when everything is hooked together properly:~
src="https://user-images.githubusercontent.com/6370918/71746068-9073ba00-2e31-11ea-83c5-8498d3a14cb8.png">
"Template Variable Presets" aka "Saved Views" are a quick shortcut that
can be added by hand or via json to dashboards in datadog, and appear in
the top left corner.
They allow you to string together common combinations of template
variable values, so if for example you want a "production us-east-2"
view of your dashboard, you could have a "production us-east-2" preset
that sets your template variables to `environment = production` and
`region = us-east-2`.
This PR adds support for template variable presets …
> Add template_variable_presets to datadog_dashboard

- datadog/resource_datadog_dashboard_list_test.go
Previously, the test would fail in ~50 % of runs, as the `screen` and `time` dashboards were created in random order.
> Stabilize TestDatadogDashListImport test by always creating resources in the same order

- website/docs/r/downtime.html.markdown
Update the documentation for the downtime scope field to more closely reflect the Datadog Documentation page - https://docs.datadoghq.com/api/?lang=bash#schedule-monitor-downtime
From issue - #430
> Update scope docs with explicit example

- datadog/resource_datadog_logs_index.go
Fixes #432 
There is an explicit catch to try and inform users that indexes can't be created and only updated after imported. However, this catch happens after we try to build an index with data that doesn't yet exist in the state. 
This change includes a quick check for the `id` field (only available if the object is in the state) before continuing. This lets us fail fast and provide a helpful error message.
> Fail fast if index isn't imported

- datadog/provider.go
This PR includes a couple extra pieces of info about the running terraform version in the user agent header:
* The Terraform SDK version (This is vendored into the provider, so this could be extracted indirectly by knowing the provider version, but this explicitly includes it)
* The terraform CLI version used to invoke the provider. 
Inspiration from - https://github.com/terraform-providers/terraform-provider-oci/blob/8ed6736016dfc4ee36cb77c80ea7f519ae2c84f4/oci/provider.go#L958
SDK Meta version from the `meta` package - https://github.com/hashicorp/terraform-plugin-sdk/blob/dbee9ba9e9bca050f5fa5d56d3232eefc64e44be/meta/meta.go
> Add terraform sdk + cli versions to user agent header

- website/docs/index.html.markdown
- website/docs/r/integration_aws.html.markdown
Missing information on AWS integration documentation while using the API Endpoint and EU version of Datadog
> doc: AWS integration & EU Datadog clarifications

- datadog/provider.go
- datadog/provider_test.go
This PR adds Generate go client V2 api to the Terraform provider
> Add Generated client v2 API 

- datadog/cassettes/TestAccDatadogDashboard_import.yaml
- datadog/cassettes/TestAccDatadogDashboard_update.yaml
Update cassette for the recently merged #421 to allow CI to account for the legend_size field.
> Update cassette for dashboard update test

- website/docs/r/monitor.html.markdown
this avoids a warning message since the 0.12.14 release (see [this](https://discuss.hashicorp.com/t/terraform-0-12-14-released/3898))
> remove ignore_changes quotes in monitor example

- datadog/resource_datadog_integration_aws.go
This PR ensures nil values are never submitted for host tags and filter tags.
> Make sure the aws host_tags and filters_tags are never nil

- datadog/resource_datadog_integration_aws.go
This PR Fixes #504 by only setting host tags, filter tags and account specific namespace rules on the http request if these values have been set by the user. 
Somehow, setting these structures while they are empty affects the serialisation of the request in such a way that the DataDog API rejects the values as being of the wrong type.
> Do not set empty structures in request to create aws integration

- go.mod
- go.sum
Fixes https://github.com/terraform-providers/terraform-provider-datadog/issues/459
> updating go-datadog-api v2.29.0, fix int issue dash id

- GNUmakefile
- README.md
Update the Makefile's `update-go-client` task to include the new client being used. (Changes the existing variable name for the zorkian client as well)
Also documents this briefly in the README.md file..
> Update make task to include new client + update README

- datadog/resource_datadog_dashboard.go
The count field is set to 0 by terraform if not set, which prevents the widget from getting any data.
Since this field is marked as deprecated, it is not expected to be set, so having a default makes sense.
> Add default to deprecated `count` field to avoid sending 0

- website/datadog.erb
- website/docs/r/dashboard.html.markdown
- website/docs/r/integration_aws.html.markdown
- website/docs/r/integration_aws_lambda_arn.html.markdown
- website/docs/r/integration_aws_log_collection.html.markdown
- website/docs/r/integration_gcp.html.markdown
- website/docs/r/integration_pagerduty.html.markdown
- website/docs/r/logs_custom_pipeline.html.markdown
- website/docs/r/logs_index.html.markdown
- website/docs/r/logs_index_order.html.markdown
- website/docs/r/logs_integration_pipeline.html.markdown
- website/docs/r/logs_pipeline_order.html.markdown
- website/docs/r/monitor.html.markdown
- website/docs/r/service_level_objective.html.markdown
Update the docs to use the latest version of the api documentation links. Most redirected properly, but there were a few, such as the integration ones, that went directly to the API Homepage instead. 
This also removes trailing whitespace for these doc files. 
Also the lambda_arn resource was documented but missing from the sidebar, this adds it in.
> Update api docs links and add lambda arn to docs

- datadog/cassettes/TestAccDatadogIntegrationPagerdutyServiceObject_Basic.yaml
- datadog/cassettes/TestAccDatadogIntegrationPagerduty_Basic.yaml
- datadog/cassettes/TestAccDatadogIntegrationPagerduty_Migrate2ServiceObjects.yaml
- datadog/cassettes/TestAccDatadogIntegrationPagerduty_TwoServices.yaml
- datadog/cassettes/TestDatadogIntegrationPagerduty_import.yaml
- datadog/import_datadog_integration_pagerduty_test.go
- datadog/resource_datadog_integration_pagerduty.go
- datadog/resource_datadog_integration_pagerduty_test.go
This PR fixes a perpetual diff observed in `datadog_integration_pagerduty.api_token`, when this value is unset:
```
- api_token           = (sensitive value)
```
I called the API and realized that it is returning a redacted string even though this is unset:
```
$ https get https://api.datadoghq.com/api/v1/integration/pagerduty "DD-API-KEY: ${DATADOG_API_KEY}" "DD-APPLICATION-KEY: ${DATADOG_APP_KEY}"
HTTP/1.1 200 OK
Cache-Control: no-cache
Connection: keep-alive
Content-Encoding: gzip
Content-Security-Policy: frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
Content-Type: application/json
DD-POOL: dogweb
Date: Fri, 22 May 2020 19:44:14 GMT
Pragma: no-cache
Set-Cookie: DD-PSHARD=113; Max-Age=604800; Path=/; expires=Fri, 29-May-2020 19:44:14 GMT; secure; HttpOnly …
```
> integration_pagerduty: fix perpetual diff in api_token

- datadog/cassettes/TestAccDatadogIntegrationAWS.yaml
- datadog/resource_datadog_integration_aws.go
- datadog/resource_datadog_integration_aws_test.go
- website/docs/r/integration_aws.html.markdown
This PR adds the newer `update` method to the AWS resource and removes the `ForceNew` workaround that was in place. 
I also updated the tests to trigger an update (using mostly the config from the documentation)
> Add full AWS Update support

- datadog/resource_datadog_dashboard.go
The newly added `indexes` field to the log_stream widget schema was being directly accessed, this PR first checks if it exists, adding a safety layer to prevent panics. 
Fixes #534 
I was able to reproduce this by creating a dashboard with a logstream widget using the provider version 2.7.0 like so:
```resource "datadog_dashboard" "free_dashboard" {
title         = "Test Log Stream Dashboard"
description   = "Created using the Datadog provider in Terraform"
layout_type   = "free"
is_read_only  = false
widget {
log_stream_definition {
logset = "19"
query = "error"
columns = ["core_host", "core_service", "tag_source"]
}
layout = {
height = 36
width = 32
x = 5
y = 51
}
}
}
```
which leads to a terraform state not having `indexes` set. Then upgrading to 2.8.0 and running a terraform apply, …
> Safely access index field

- website/docs/r/monitor.html.markdown
Correct indent on the `datadog_monitor` in document.
> Fix indent in datadog_monitor

- datadog/provider_test.go
This change will allow to mock the tests using gock since we will be able to pass the DefaultHttpClient that is used by default by gock.
> Allow to pass http client when creating test provider

- GNUmakefile
- datadog/resource_datadog_dashboard.go
- website/docs/r/dashboard.html.markdown
Also increase test timeout 
Fixes https://github.com/terraform-providers/terraform-provider-datadog/issues/349
> add readonly url field to dashboard

- website/docs/index.html.markdown
Adding a space character so that the markdown reference on the documentation landing page correctly renders the bulleted list.
> Fix markdown rendering on argument reference

- datadog/resource_datadog_integration_pagerduty.go
- website/docs/r/integration_pagerduty.html.markdown
- website/docs/r/integration_pagerduty_service_object.html.markdown
The pagerduty integration is a legacy resource used when we didn't use
webhooks. It's a singleton, which means it doesn't fit properly into the
terraform model, each instance overriding the previous one. This
prevents its deletion, and deprecate it.
Closes #564
> Deprecate pagerduty integration

- datadog/cassettes/TestAccDatadogSyntheticsAPITest_BasicNewAssertions.yaml
- datadog/cassettes/TestAccDatadogSyntheticsAPITest_UpdatedNewAssertions.yaml
- datadog/cassettes/TestAccDatadogSyntheticsAPITest_importBasicNewAssertions.yaml
- datadog/resource_datadog_synthetics_test_.go
- datadog/resource_datadog_synthetics_test_test.go
- website/docs/r/synthetics.html.markdown
This adds 2 requests fields that we didn't expose previously. As `request_headers`, this needs to be outside of the `request` attribute but it only supports basic types.
Closes #305
> Add support for basicAuth and query in Synthetics resource

- .goreleaser.yml
This ensures that `version.ProviderVersion` is properly set even when building with `goreleaser`.
> Properly setup version.ProviderVersion when using goreleaser

- .github/workflows/release.yml
Adds a workflow to release (will create a release draft to be checked and published manually) when a new semver tag is pushed.
> Add releasing Github workflow

- GNUmakefile
- datadog/cassettes/TestAccDatadogDashboard_import.yaml
- datadog/cassettes/TestAccDatadogDashboard_update.yaml
- datadog/cassettes/TestAccDatadogTimeboard_update.yaml
- datadog/resource_datadog_dashboard.go
- datadog/resource_datadog_dashboard_test.go
- datadog/resource_datadog_timeboard.go
- datadog/resource_datadog_timeboard_test.go
- go.mod
- go.sum
- vendor/github.com/DataDog/datadog-api-client-go/.apigentools-info
- vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_change_widget_request.go
- vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_distribution_widget_request.go
- vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_heat_map_widget_request.go
- vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_host_map_request.go
- vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_monitor_type.go
- vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_query_value_widget_request.go
- vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_scatter_plot_request.go
- vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_table_widget_request.go
- vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_timeseries_widget_request.go
- vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_toplist_widget_request.go
- vendor/github.com/DataDog/datadog-api-client-go/run-go-tests.sh
- vendor/github.com/DataDog/datadog-api-client-go/run-tests.sh
- vendor/github.com/DataDog/datadog-api-client-go/version.go
- vendor/modules.txt
Add security signals and RUM events as data sources for Timeseries, Query Value, Table and Top List dashboard widgets.
This PR is related to this [go api PR](https://github.com/zorkian/go-datadog-api/pull/304). It will be merged with the version bump after go api PR is merged and a new version is released.
> New data sources for widgets

- docs/data-sources/ip_ranges.md
- docs/data-sources/monitor.md
- docs/guides/monitors.md
- docs/index.md
- docs/resources/dashboard.md
- docs/resources/dashboard_list.md
- docs/resources/downtime.md
- docs/resources/integration_aws.md
- docs/resources/integration_aws_lambda_arn.md
- docs/resources/integration_aws_log_collection.md
- docs/resources/integration_azure.md
- docs/resources/integration_gcp.md
- docs/resources/integration_pagerduty.md
- docs/resources/integration_pagerduty_service_object.md
- docs/resources/logs_archive.md
- docs/resources/logs_custom_pipeline.md
- docs/resources/logs_index.md
- docs/resources/logs_index_order.md
- docs/resources/logs_integration_pipeline.md
- docs/resources/logs_pipeline_order.md
- docs/resources/metric_metadata.md
- docs/resources/monitor.md
- docs/resources/screenboard.md
- docs/resources/service_level_objective.md
- docs/resources/synthetics.md
- docs/resources/timeboard.md
- docs/resources/user.md
More upgrades to docs as recommended by the official docs at [1]:
* Remove unused frontmatter values, adapt `page_title` attributes
* Use `Data Source` resp. `Resource` after the name of the data source resp. resource in the title. 
[1] https://www.terraform.io/docs/registry/providers/docs.html
> Upgrade docs according to the latest recommendations

- datadog/cassettes/TestAccDatatogSyntheticsLocation_existing.yaml
- datadog/data_source_datadog_synthetics_locations.go
- datadog/data_source_datadog_synthetics_locations_test.go
- datadog/provider.go
- docs/data-sources/synthetics_locations.html.md
- docs/data-sources/synthetics_locations.md
Attempts to address #217.
related to https://github.com/terraform-providers/terraform-provider-datadog/issues/381
> Add synthetics locations data source

- datadog/resource_datadog_logs_custom_pipeline.go
If query is empty, the filter we try to build is an empty map (even if
it has a length...), so casting will fail. Validate the field so that it
doesn't happen.
Closes #572
> Validate query field of pipeline filter

- datadog/resource_datadog_downtime.go
We want to ignore the diff even if start is set "right now". This fixes a test flake like [this](https://dev.azure.com/datadoghq/terraform-provider-datadog/_build/results?buildId=20841&view=logs&j=abc39910-4c32-5be0-0b39-6d3f303c7218&t=632788a2-3bb3-5d1a-83fe-bfd285143df8&l=573).
> Fix DiffSuppressFunc for downtime start

- datadog/resource_datadog_metric_metadata_test.go
Because these two tests operate on the same metric, we can't run them in parallel. The "proper" fix for this test case that would protect it from even two concurrent runs of the test suite will involve a bit more work, but this should help considerably in the meanwhile.
> Decrease flakiness of metric metadata tests by not running in parallel

- docs/resources/synthetics.md
This PR updates the documentation for the `datadog_synthetics_test` resource, parameter `min_location_failed` to match the [Datadog API docs](https://docs.datadoghq.com/api/v1/synthetics/) in order to provide more clarity.
> [Synthetics] Fix min_location_failed parameter description

- datadog/resource_datadog_dashboard.go
When importing a dashboard with a template variable with no prefix, the
provider panics with the following error message:
```
panic: runtime error: invalid memory address or nil pointer dereference
2020-08-10T13:42:16.345+0200 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1bddcf1]
2020-08-10T13:42:16.345+0200 [DEBUG] plugin.terraform-provider-datadog_v2.12.1:
2020-08-10T13:42:16.345+0200 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: goroutine 81 [running]:                                                                                                     2020-08-10T13:42:16.345+0200 [DEBUG] plugin.terraform-provider-datadog_v2.12.1: github.com/terraform-providers/terraform-provider-datadog/datadog.buildTerraformTempla …
```
> Prevent nil pointer dereference in dashboard import

- datadog/resource_datadog_monitor.go
This fixes a build error happening with the new go release, which seems
to be an actual bug.
> Fix build error with go 1.15

- datadog/provider.go
- docs/index.md
The current approach was checking that the creds where not set, but it
doesn't make much sense to have such a restriction. Let's skip
validation altogether when `validate` is set to `false`.
Closee #640
> Completely skip creds validation when validate is false

- docs/resources/synthetics.md
Fix the formatting in the [terraform documentation website for nested arguments](https://www.terraform.io/docs/providers/datadog/r/synthetics.html#argument-reference). I suppose their website does not support more than one level of nesting in objects, and we have arguments that have two levels.
> [Synthetics] Fix documentation format for nested arguments

- docs/resources/synthetics.md
Threw me off for a good bit.
`Retry` is of type `TypeList`
> Update documentation for synthetic retry syntax

- datadog/resource_datadog_dashboard.go
When upgrading from a version with the dashboard_list attribute on
dashboard, it would generate a diff for dashboard_list_removed on first
apply. Let's clear it to remove that diff.
> Clear dashboard_list_removed diff

- docs/resources/monitor.md
A few of them were missing from the monitor resource documentation.
> Document monitor types accurately

- datadog/data_source_datadog_dashboard_list.go
- datadog/provider.go
While reading through the code I happened to notice a function had a small misspelling
- `s/boar/board/`
...unless Datadog plans to change the dog 🐶  to a boar 🐗 in an upcoming marketing rebranding.
> Correct the spelling of dashboard in a private function

- go.mod
- go.sum
- vendor/github.com/DataDog/datadog-api-client-go/.apigentools-info
- vendor/github.com/DataDog/datadog-api-client-go/api/v1/datadog/model_synthetics_step_type.go
- vendor/modules.txt
Update go client to fix https://github.com/DataDog/terraform-provider-datadog/issues/706
The client update includes the missing step types.
> [Synthetics] Update go client

- .pre-commit-config.yaml
Bump the version of prettier to match the revision used in the pre-commit hook. 
This mismatch was causing CI failures as we were using an out of date version that didn't include CLI flags we needed. Example of failure run - https://github.com/DataDog/terraform-provider-datadog/pull/729/checks?check_run_id=1329277125
> Bump prettier version to 2.1.1 to match the existing config

- datadog/resource_datadog_synthetics_test_.go
The config field for old synthetics tests doesn't contain the variables
field, so accessing it directly fails with a pointer exception. Use the
getter that protects from such a problem.
Closes #731
> Handle missing variables field

- docs/resources/monitor.md
Reverts DataDog/terraform-provider-datadog#739 
We don't want to make that public public yet.
> Revert "Document monitor priority"

- README.md
The package `time/tzdata` is used as a dependency.
> Update minimum version go 1.15 in README

- datadog/resource_datadog_synthetics_test_.go
Set the client certificate content in synthetics config to prevent leaking content in CLI.
> [Synthetics] Set client certificate content as sensitive

- docs/resources/synthetics_test.md
I know it's minor and kinda nit-picky, but I have just noticed this minor inconsistency in the docs.
> Reflect synthetics type in resource name example

- docs/index.md
Recently published a hands-on tutorial that may be a good addition to the docs.
https://learn.hashicorp.com/tutorials/terraform/datadog-provider?in=terraform/use-case
> Add link to Learn tutorial

- datadog/resource_datadog_service_level_objective.go
- docs/resources/service_level_objective.md
Add `force_delete` to the SLO resource schema in the same way we have it for the monitor resource. 
This already exists in the API layer, so this brings TF up to date.
> Add force_delete to SLO resource

- datadog/resource_datadog_user.go
If roles field is set we need to make sure that we're using v2,
otherwise we fall back on the standard access role.
Closes #777
> Automatically upgrade users when `roles` is set

- datadog/key.go
- datadog/key_test.go
This can be used to simplify access to deeply nested data structures within Terraform's `ResourceData`.
> Add the ResourceDataKey utility struct

- datadog/provider.go
This was broken by the client migration a while back.
Closes #789
> Enable UpdateLogsIndexOrder

- docs/resources/monitor.md
Reverts DataDog/terraform-provider-datadog#741
Pulls back in https://github.com/DataDog/terraform-provider-datadog/pull/739.
We're now at 50% rollout, should be completed next day or two. I assume this won't show up until the next release?
> Revert "Revert "Document monitor priority""

- README.md
Remove the section that talks about GOPATH/the version of go required. This is outdated, and the version of go required is earlier in the README under `## Requirements`
> Remove separate section about GO requirements

- datadog/cassettes/TestAccDatadogMonitor_Basic_float_int.yaml
- datadog/cassettes/TestAccDatadogMonitor_MuteUnmuteSpecificScopes.yaml
- datadog/cassettes/TestAccDatadogMonitor_SilencedRemove.yaml
- datadog/cassettes/TestAccDatadogMonitor_SilencedUpdatePastTimestamp.yaml
- datadog/cassettes/TestAccDatadogMonitor_Updated.yaml
- datadog/cassettes/TestAccDatadogMonitor_UpdatedToRemoveTags.yaml
- datadog/resource_datadog_monitor.go
- datadog/resource_datadog_monitor_test.go
And adds a test to cover updating priorities.
cc @DataDog/monitor-app
> [monitor] Fix updating priorities.

- datadog/resource_datadog_monitor.go
If we have a 404 in the retry, we need to check the ID again outside of
it.
Closes #822
> Handle result in 404 case in monitor

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
Timeout is only supported by HTTP tests for now.
This also removes an unused variable.
Closes #828
> Remove timeout from non-HTTP tests docs

- datadog/resource_datadog_user.go
Add deprecation notice to the access_role field, this isn't used in the v2 version of the endpoint and is replaced by roles. 
In my testing, you only get the Deprecation Warning log if this is explicitly set in your config, even though we set a default on this field.
> Add deprecation field to User -> access_role

- datadog/resource_datadog_monitor.go
- docs/resources/monitor.md
timeout_h is of type Int and defaults to `false` according to the docs.
There are no defaults defined in the code, so i removed the comment
about the default.
> Fixed error in doc where Int defaults to `false`.

- GNUmakefile
Bump timeout to be 20 minutes instead of 15. 
As new resources and endpoints are being added, the tests seem to be starting to hit the 15 minute timeout
> Update timeout on gotestsum to be 20 minutes

- datadog/resource_datadog_synthetics_test_.go
- datadog/resource_datadog_synthetics_test_test.go
The items in the location list need to be unique, and server can
re-order them, so using a set is the best course of actions.
> Turn synthetics test locations into a set

- docs/data-sources/monitor.md
- docs/data-sources/security_monitoring_rules.md
- docs/data-sources/synthetics_locations.md
- docs/index.md
- docs/resources/integration_aws.md
- docs/resources/integration_aws_log_collection.md
- docs/resources/integration_azure.md
- docs/resources/security_monitoring_default_rule.md
- docs/resources/security_monitoring_rule.md
- docs/resources/synthetics_global_variable.md
- docs/resources/synthetics_private_location.md
- docs/resources/synthetics_test.md
- examples/data-sources/datadog_monitor/data-source.tf
- examples/data-sources/datadog_security_monitoring_rules/data-source.tf
- examples/data-sources/datadog_synthetics_locations/data-source.tf
- examples/provider/provider.tf
- examples/resources/datadog_integration_aws/resource.tf
- examples/resources/datadog_integration_aws_log_collection/resource.tf
- examples/resources/datadog_integration_azure/resource.tf
- examples/resources/datadog_security_monitoring_default_rule/resource.tf
- examples/resources/datadog_security_monitoring_rule/resource.tf
- examples/resources/datadog_synthetics_global_variable/resource.tf
- examples/resources/datadog_synthetics_private_location/resource.tf
- examples/resources/datadog_synthetics_test/resource.tf
Using tf 0.12, I ran `terraform fmt -recursive examples` and regenerated the docs.
(Note, due to the bug with generating security_monitoring_rules data-source docs, I have to manually change Computed: false and make an edit in the generated doc). 
This should have no functional impact, just cleans up the examples according to `terraform fmt`. 
Using terraform 0.14 to run `fmt` causes the same output, except for the index where it tries to remove `${` around the variables here - https://github.com/DataDog/terraform-provider-datadog/blob/master/examples/provider/provider.tf#L35-L36 However this syntax is needed for earlier versions of terraform.
> Run terraform fmt on examples and regenerate

- datadog/resource_datadog_dashboard.go
- docs/resources/dashboard.md
In the documentation about `event_stream_definition`, the description of the attribute `event_size` states the following:
- **event_size** (String, Optional) The alignment of the widget's title. One of `left`, `center`, or `right`. 
This is the description of the **title_align** attribute. The description according to the Datadog API documentation should be the one proposed in this Pull Request.
Reference: [Event Stream Widget](https://docs.datadoghq.com/dashboards/widgets/event_stream/)
> Correct event_stream_definition documentation for event_size

- datadog/provider.go
- datadog/resource_datadog_logs_index.go
- datadog/resource_datadog_logs_index_order.go
Avoid consistency issues, due to replication delays, caused by calling the GET endpoint right after POST/PUT
Also fixes some linting warnings
> Improve consistency by using response from POST/PUT requests directly to save state

- .azure-pipelines/all.yml
Add a scheduled 12 hour cron to the Azure Pipeline. 
This will ensure we run the CI on master if there are no PRs for a bit and let us bisect the start of potential issues.
> Add 12 hour cron to AZP runs

- .azure-pipelines/all.yml
- .github/workflows/test.yml
- DEVELOPMENT.md
- GNUmakefile
This PR aims to cleanup the Makefile and the way tests are run:
* Adds rerun-failed to gotestsum so we can retry individual errors
* The default here is sane, the test will be retried twice, and if more than 10 tests are failing, tests won't be retried at all by gotestsum since there's likely a larger issue at play
* gotestsum requires you pass in the packages to it, so I also moved the `go list` to be part of the invocation to `gotestsum` instead of `go test` flags. 
* Add a new `make testall` command that will run both acceptance and unit tests
* Stop `make test` from running the acceptance tests in record mode
* Set the default `RECORD` to `false` in the makefile and allow it to run `make testacc` or `make testall` with the flag to control if we playback or record during testing
* …
> Cleanup makefile, add testall, add rerun-failed

- .azure-pipelines/all.yml
- datadog/provider_test.go
- go.mod
- go.sum
Get us more in-line with how we're doing traces in the go client. See - https://github.com/DataDog/datadog-api-client-go/pull/500
> Update traces from the provider

- datadog/resource_datadog_integration_pagerduty.go
- docs/resources/integration_pagerduty.md
Until we have a way to manage schedules to appear in the event stream,
this is still required.
Closes #665
> Remove deprecation on PagerDuty resource

- .github/workflows/test.yml
- GNUmakefile
- LICENSE-3rdparty.csv
- scripts/license-check.sh
* Updates the 3rd party csv file to note all the deps we have in go.sum
* Adds a new script `license-check.sh`, essentially a copy from the datadog-api-client-go with a change from `echo` -> `printf`
* Run the script via `make license-check` and add this to the github action CI
> Update 3rd Party License file and add check to CI

- docs/resources/dashboard.md
- examples/resources/datadog_dashboard/resource.tf
`widget_layout` parameter is typically used with `layout_type` free dashboard. Remove it from the ordered layout dashboard resource example.
> Fix dashboards example resource

- datadog/resource_datadog_downtime.go
This PR checks if monitor_id is nil before setting it. Previous approach was causing value of 0 to be stored in state. See terraformer issue here: https://github.com/GoogleCloudPlatform/terraformer/issues/818
> Explicitly check monitor_id for nil value

- datadog/resource_datadog_synthetics_test_.go
These links were pointing to an older page and were a bit confusing. We can't link to the exact spot in the table that's being referenced, but this should at least get readers a little closer to the info they need.
> (docs) Update links to datadog documentation

- datadog/data_source_datadog_dashboard.go
The `/api/v1/dashboard` endpoint can sometimes result in a 504 timeout due to the extended processing time when there's many dashboards to list out. This PR adds a simple retry in hopes that a subsequent request is successful.
> [dashboard datasource] Retry on 504 errors

- datadog/resource_datadog_synthetics_test_.go
To avoid leaking sensitive data we [store a hash of the client certificate field in the state](https://github.com/DataDog/terraform-provider-datadog/pull/835). The issue is that in the update process of terraform, we get the values from the state and not from the config. This means we send the hashed version of the client certificate instead of the correct value, and it breaks tests since the configuration is not valid anymore.
This PR fixes this by checking if the client certificate looks like a sha256 hash, and if that's the case we don't send the value (in the backend the value is write-only and if the value is not present it will not be overwritten). It's a bit hacky but we're already doing a check like this to save the state.
Unfortunately this can't be checked in the tests (we need …
> [Synthetics] Prevent certificate update with wrong value

- datadog/resource_datadog_security_monitoring_default_rule.go
This PR adds filtering (`require` and `suppress`) support to the datadog default security monitoring rules.
Ref. https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/security_monitoring_default_rule
No acceptance tests have been implemented cause of a limitation in the `terraform-plugin-sdk` which doesn't currently allow checking for modifications on imported resources. See details on https://github.com/DataDog/terraform-provider-datadog/pull/956
> [Feature] Add datadog default security monitoring rule filters

- datadog/data_source_datadog_dashboard.go
Relates to https://github.com/DataDog/terraform-provider-datadog/pull/975 
In addition to occasional 504's, the `/api/v1/dashboard` endpoint also appears to return occasional 502's. This PR updates the logic to attempt to retry the operation for both 504's and 502's as that appears to do the trick.
> [datasource dashboard] Retry on 502s

- datadog/resource_datadog_synthetics_test_.go
If params is empty, then we fail to parse the map and it ends up in a
panic.
> Fix panic when converting params

- datadog/resource_datadog_monitor.go
It shouldn't check for locked, as it's still present in the state,
and thus remove the possibility of updating it.
> Fix monitor restricted_roles diff

- datadog/resource_datadog_monitor.go
It appears that in addition to 502's, we can sometimes get a 504 and simply retrying avoids a complete Terraform run failure.
> [monitor resource] Retry on 504

- datadog/resource_datadog_integration_aws.go
A 400 on GET means the integration is not installed.
In this case, set ID to `""` so terraform knows it has to create the integration.
Fixes #1046
> Mark AWS account as non existent if GET returns 400 when AWS integration not installed

- datadog/resource_datadog_monitor.go
- docs/resources/monitor.md
Under the schema for `monitor_thresholds`, `critical` is listed as the "recovery threshold" rather than "threshold".
> Update monitor `critical` threshold documentation

- datadog/resource_datadog_logs_custom_pipeline.go
- docs/resources/logs_custom_pipeline.md
From "log attribute or tag", it's not clear what the permitted values of `source_type` and `target_type` are, exactly (`log attribute` and `tag`? `log-attribute` and `tag`? `attribute` and `tag`? ...). The examples all use `tag`, so the correct way to specify attribute isn't clear. The API docs use code formatting for `attribute` and `tag` and make it clear (see option 6 in [the "create a pipeline" section][1] of the API docs):
Doing the same here would increase clarity.
[1]: https://docs.datadoghq.com/api/latest/logs-pipelines/#create-a-pipeline
> Use code formatting in description for attribute remapper

- datadog/resource_datadog_integration_aws_lambda_arn.go
Errors are returned in the response object of a 200 response
Fixes #1094
> Properly catch error response from AWS Logs integration

- datadog/resource_datadog_monitor.go
There are still cases where the api will return `query alert` for `metric alert` types. This PR introduces the previous removed `DiffSuppressFunc`.
Fixes #1100
> Re-introduce monitor type diff suppression for query/metric alerts

- datadog/resource_datadog_logs_index.go
- docs/resources/logs_index.md
from https://docs.datadoghq.com/api/latest/logs-indexes/#create-an-index
it seems to be integers
also getting errors while trying to apply with the current version:
Error: daily_limit: '' expected type 'string', got unconvertible type 'int64'
Closes #1113
> Fix day_limit and retention type log index attributes

- datadog/resource_datadog_logs_index.go
- docs/resources/logs_index.md
From https://docs.datadoghq.com/api/latest/logs-indexes/#create-an-index it seems like `daily_limit` is optional which would align with the UI as well.
> Fix `retention_days` and `daily_limit` attributes 

- datadog/resource_datadog_integration_aws_tag_filter.go
- docs/resources/integration_aws_tag_filter.md
EU endpoints are now supported. This PR removes the US endpoint only constraint from documentation.
> Remove US only constraint from docs

- datadog/provider.go
- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
- go.mod
- go.sum
Update the go client and update the provider to stop using an enum for `tick_every` and accept any integer.
> [Synthetics] Update `tick_every` to use int

- datadog/resource_datadog_logs_index.go
- docs/resources/logs_index.md
This PR ensures we properly update `daily_limit` and `retention_days` fields on Update request. 
Resource update + import has been manually tested. We cannot implement a test feature at the moment as Logs index creation is not supported.
> Fix logs_index update method

- datadog/data_source_datadog_security_monitoring_rules.go
- datadog/resource_datadog_security_monitoring_rule.go
- datadog/tests/data_source_datadog_security_monitoring_rules_test.go
- datadog/tests/resource_datadog_security_monitoring_rule_test.go
Was missing from https://github.com/DataDog/terraform-provider-datadog/pull/1130, not sure how the create and update tests were passing correctly if we didn't save the value in the state 😕
> Save `has_extended_title` and `enabled` in state

- docs/resources/integration_aws_log_collection.md
- docs/resources/integration_aws_tag_filter.md
- examples/resources/datadog_integration_aws_log_collection/resource.tf
- examples/resources/datadog_integration_aws_tag_filter/resource.tf
Noted in the public docs a small typo for resources:
- `datadog_integration_aws_log_collection`
- `datadog_integration_aws_tag_filter`
This should fix the typos on next documentation generate.
> Fixed Terraform examples for  `datadog_integration_aws_log_collection/tag_filter`

- docs/resources/integration_slack_channel.md
- examples/resources/datadog_downtime/import.sh
- examples/resources/datadog_integration_aws/import.sh
- examples/resources/datadog_integration_aws_lambda_arn/import.sh
- examples/resources/datadog_integration_aws_log_collection/import.sh
- examples/resources/datadog_integration_slack_channel/import.sh
- examples/resources/datadog_integration_slack_channel/resource.tf
Noted there wasn't a `terraform import` example for the `datadog_integration_slack_channel` resource type.
E.g.
```sh
terraform import datadog_integration_slack_channel.test_channel "foo:#test_channel"
```
> Documentation - adding `datadog_integration_slack_channel` slack import example

- datadog/resource_datadog_synthetics_test_.go
Some assertion type have an integer target, this adds the missing ones
Fixes #1160
> Fix missing integer type assertion targets

- docs/resources/synthetics_test.md
- examples/resources/datadog_synthetics_test/resource.tf
- templates/resources/synthetics_test.md.tmpl
- Clarifies the use of `config_variable` for global variables
- Fixes the format and name of the `browser_step` bloc
- I can't currently get the `make docs` command to work properly
```bash
/Users/pcothenet/Projects/terraform-provider-datadog/scripts/generate-docs.sh: line 19: tfplugindocs: command not found
```
- Downloading the latest binary for `tfplugindocs` generates more than 46 changes to the docs, which are out of scope for my fix.
- I'm happy letting you take it from here.
> Update synthetics docs for global variable + browser test

- .azure-pipelines/all.yml
- .github/workflows/test.yml
- GNUmakefile
- docs/resources/synthetics_test.md
- examples/resources/datadog_synthetics_test/resource.tf
- scripts/fmtcheck.sh
- tools/tools.go
- Use Golang 1.16 that's used for building the provider
- Add Golang 1.17 new build syntax
- Stop running fmtcheck on integration tests, it's already run in unit tests
- Fix fmtcheck that wouldn't exit with an exit code properly on terraform fmt
> Fix azure pipelines build

- datadog/resource_datadog_dashboard.go
- docs/resources/dashboard.md
- examples/resources/datadog_dashboard/resource.tf
- go.mod
- go.sum
This PR adds the `available_values`  property to template variables.
**Related PRs:**
- https://github.com/DataDog/datadog-api-spec/pull/1133
- https://github.com/DataDog/dogweb/pull/63689
> Add `available_values` property to dashboard template variables

- datadog/resource_datadog_dashboard_json.go
The data structure may not be complete when StateFunc is called, so we
need to assert that the cast works properly.
Closes #1196
> Validate widgets cast in dashboard JSON

- datadog/resource_datadog_slo_correction.go
- go.mod
- go.sum
Update datadog-api-client-go to latest version 1.4.0
> Update datadog-api-client-go to latest version v1.4.0

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
update of #1215
If you don't specify this property, you'll see the following error:
> 400 Bad Request: {"errors": ["properties.options.required: 'device_ids' is a required property...
> datadog_synthetics_test: device_ids is required for browser type only

- datadog/resource_datadog_synthetics_test_.go
> Fix synthetics browser test `upload-files` step

- datadog/resource_datadog_downtime.go
- datadog/tests/resource_datadog_downtime_test.go
Fixes https://github.com/DataDog/terraform-provider-datadog/issues/1193
> Set only one of timestamp or date format for start and end to avoid inconsistent plans

- datadog/resource_datadog_monitor.go
- docs/resources/monitor.md
`A boolean indicating whether changes to to this monitor` reads poorly because of the back to back `to`s
Remove one of the two `to`s
I ran:
```
$ git grep 'A boolean indicating whether changes to to'
```
to find all instances of this string and then changed them
I ran `make docs` and everything seemed to work
> Fix typo in the datadog_monitor page

- datadog/resource_datadog_synthetics_test_.go
Do not panic when empty or nil `request_definition` is passed for api_step
> Handle empty `request_definition`

- docs/resources/monitor.md
- examples/resources/datadog_monitor/resource.tf
`timeout_h` values greater than 24 hours are not supported. This example has unfortunately led to many invalid monitors.
> [examples] Fix invalid monitor timeout_h example

- datadog/resource_datadog_monitor_json.go
On resource name change the old is still there, and the new is empty, so there
the `new.(string)` is empty, so `newAttrMap` is `interface{}`
And terraform panics on that line.
This defensive programming action fixes the panic, but I think (guess?) that the code should never
get to this point on this case.
> fix: panic on resource name change

- datadog/resource_datadog_monitor_json.go
name and message are trimmed server side so we get a perpetual diff if
those fields start or end with spaces. This fixes it by tweaking the
state function.
Closes #1289
> Fix perpetual diff on some monitor JSON fields

- datadog/resource_datadog_monitor.go
Fixes terraformer import of monitors with `new_group_delay`.
> Dont set `new_host_delay` if its not returned by api

- docs/resources/dashboard_list.md
- docs/resources/logs_archive_order.md
- docs/resources/logs_index_order.md
- docs/resources/logs_pipeline_order.md
- examples/resources/datadog_dashboard_list/resource.tf
- examples/resources/datadog_logs_archive_order/resource.tf
- examples/resources/datadog_logs_index_order/resource.tf
- examples/resources/datadog_logs_pipeline_order/resource.tf
Follow up to: https://github.com/DataDog/terraform-provider-datadog/pull/1271
> Remove unnecessary `depends_on` in examples

- datadog/resource_datadog_authn_mapping.go
Supporting ReadContext for Datadog SAML Authentication Mapping.
Not adding tests because they should be covered by #1344.
> [ACCESS-597] Support ReadContext for Datadog SAML Authentication Mapping.

- datadog/resource_datadog_monitor.go
- docs/resources/monitor.md
`restricted_roles` are now generally available via the API for all customers. This updates the terraform docs to match how we (will) document it in the API docs.
> [monitor] Update docs for restricted_roles.

- datadog/resource_datadog_monitor.go
- docs/resources/monitor.md
With monitor restricted roles being GA, this marks the previous locked as deprecated.
@DataDog/monitor-app
> [datadog_monitor] Mark locked as deprecated

- datadog/resource_datadog_security_monitoring_rule.go
Adds a default of "count" for the aggregation in queries in security
rules. The previous default was an empty string, which caused a
validation error at the API level.
This change makes sure we're using the same default as the web app.
> [datadog_security_monitoring_rule] Add default for aggregation

- datadog/resource_datadog_metric_metadata.go
- docs/resources/metric_metadata.md
Clarify supported metric types, `gauge`, `rate` on the `resource_datadog_metric_metadata` document.
`resource_datadog_metric_metadata` depends on [Edit metric metadata](https://docs.datadoghq.com/api/latest/metrics/#edit-metric-metadata), so metric types must be `gauge` or `rate`. That should be documented.
> [resource_datadog_metric_metadata] Clarify supported metric types

- datadog/resource_datadog_monitor.go
- docs/resources/monitor.md
Update description of monitors `timeout_h` option to make it consistent with the [API](https://docs.datadoghq.com/api/latest/monitors/#create-a-monitor).
> Add documentation on limits for Monitors timeout_h option

- docs/guides/monitors.md
- docs/resources/monitor.md
- examples/guides/anomaly_monitor.tf
- examples/guides/process_monitor.tf
- examples/guides/watchdog_monitor.tf
- examples/resources/datadog_monitor/resource.tf
Customers copy paste the example resource config assuming this is somewhat of a default monitor config. This PR removes unnecessary options that the customer doesn't always need immediately.
Also updates monitor resource examples in guide page.
> Update Monitors Terraform Resource Example

- .github/CODEOWNERS
The new handle is `k9-cloud-security-platform`.
> Rename the security-monitoring Github team

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
The documentation linked for locations is not clear, change it for the data source so the user can have a better idea of the locations they can use.
> [Synthetics] Change documentation url for locations

- datadog/resource_datadog_security_monitoring_default_rule.go
- docs/resources/security_monitoring_default_rule.md
Closes: https://github.com/DataDog/terraform-provider-datadog/issues/1578
> [datadog_security_monitoring_default_rule] Add missing schema attribute `type`

- datadog/data_source_datadog_security_monitoring_rules.go
- datadog/resource_datadog_security_monitoring_default_rule.go
- datadog/resource_datadog_security_monitoring_rule.go
- datadog/tests/data_source_datadog_security_monitoring_rules_test.go
- docs/resources/security_monitoring_rule.md
- go.mod
- go.sum
There will be a separate PR to introduce support for signal correlation rule type since it requires schema changes.
> [datadog_security_monitoring] Update security-monitoring to use new api format

- datadog/resource_datadog_logs_metric.go
Resolves the crash exposed in #1607 where `for_each` meta-argument results in nil `group_by` blocks.
> [logs_metrics] add nil check to Logs Metrics getGroupBys

- docs/resources/dashboard_json.md
- examples/resources/datadog_dashboard_json/import.sh
Originally raised by #1609 , this adds the example that the docs are autogenerated from
> Add import documentation for datadog_dashboard_json

- datadog/resource_datadog_service_definition_yaml.go
Correctly set id to nil when resource does not exist.
> [datadog_service_definition_yaml] Move `404 statusCode` check into the error check block

- datadog/resource_datadog_integration_aws.go
Raise an appropriate error when the importing resource does not exist. Closes https://github.com/DataDog/terraform-provider-datadog/issues/1642
> [datadog_integration_aws] Properly handle missing resource when importing

- datadog/resource_datadog_logs_archive.go
- docs/resources/logs_archive.md
Properly mark `path` attribute as optional. Closes: https://github.com/DataDog/terraform-provider-datadog/issues/1646
> [datadog_logs_archive] mark `path` as optional

- datadog/internal/utils/tags.go
- datadog/internal/utils/tags_test.go
- datadog/resource_datadog_service_definition_yaml.go
- datadog/resource_datadog_service_level_objective.go
Adds a tag normalization function for use with any fields that conform to USM Tagging (https://docs.datadoghq.com/getting_started/tagging/)
Affects service_definition_yaml and service_level_objective
> [service_definition_yaml] Add tag normalization util

- docs/resources/metric_metadata.md
- docs/resources/metric_tag_configuration.md
- examples/resources/datadog_metric_metadata/import.sh
- examples/resources/datadog_metric_tag_configuration/import.sh
Adds example documentation for metric_metadata and metric_tag_configuration
Resolves #1705
> [datadog_metric_metadata] Add import examples

- datadog/resource_datadog_cloud_configuration_rule.go
- go.mod
- go.sum
> [provider] Bump `datadog-api-client` to 2.7.0

- datadog/resource_datadog_service_account.go
- go.mod
- go.sum
Service account got moved. This code needs to be updated because the provider currently doesn't compile with a go client version bump.
Spec update: https://github.com/DataDog/datadog-api-spec/pull/2030
> [datadog_service_account] fix migration compilation error

- datadog/resource_datadog_dashboard.go
- docs/resources/dashboard.md
Adds note that `event_size` is required when using a list stream with the `event_stream` data source
> [datadog_dashboards] Docs update for event_size field in dashboard list_stream_definition

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
Original PR by @itzsaga in #1784, continuing here due to CI permissions
> Recently ran into an error using this provider:
> 
> ```
> │ Error: error updating synthetics API test from https://api.datadoghq.com/api/v1/synthetics/tests/api/qn8-4rv-gge: 400 Bad Request: {"errors":["properties.options.properties.monitor_options.properties.renotify_interval.enum: 5 is not one of [0, 10, 20, 30, 40, 50, 60, 90, 120, 180, 240, 300, 360, 720, 1440]
> ```
> 
> This PR updates the documentation to more explicitly list the valid values for the `sythetics_test` `renotify_interval` values.
> Update docs for synthetics_test renotify_interval

- datadog/resource_datadog_logs_index_order.go
- docs/resources/logs_index_order.md
Neither name or ID is stored on the backend and neither really represents anything. This makes name optional and computed, so if the user omits the field, the provider falls back to a hardcoded ID string "logs_index_order".
This change fixes drift when first importing a logs index order. Closes #1665
> [datadog_logs_index_order] Make name optional and computed

- datadog/resource_datadog_downtime.go
We compare with the times of the children, so there is going to be a change after every recurrence. Let's ignore it instead, at the expense of losing UI drifts. This was the intent of the original recurrence support but wasn't done.
> [datadog_downtime] Ignore start/end comparison on recurring downtimes

- datadog/resource_datadog_monitor.go
- docs/resources/monitor.md
the search field is incorrectly marked optional. 
relevant slack thread: https://dd.slack.com/archives/CFAPKSARY/p1678700526803439
> [datadog_monitor] Make search required for f&f monitors

- datadog/resource_datadog_metric_tag_configuration.go
`key:value` end of string parsing with `[^:]` is too loose, allows special characters that aren't allowed in tags
Tags are allowed to end in `:`, so this relaxes that validation and fixes the above issue
> [datadog_metric_tag_configuration] Fix tag validation for metric tags configs

- datadog/resource_datadog_security_monitoring_default_rule.go
Update terraform warning message detail on default rule depreciation for more clarity per [the following issue](https://datadoghq.atlassian.net/jira/software/c/projects/SEC/boards/1549?modal=detail&selectedIssue=SEC-7439):
> [datadog_security_monitoring_default_rule] Update deprecation warning for security monitoring rule

- datadog/resource_datadog_security_monitoring_default_rule.go
Revision from [this PR](https://github.com/DataDog/terraform-provider-datadog/pull/1827) to add spaces at the end of each sentence.
> [datadog_security_monitoring_default_rule] Add spaces to deprecation message

- datadog/resource_datadog_dashboard.go
Empty formulas may pass schema validation but will be returned as nil in the provider, let's protect against them.
Closes #1830.
> [datadog_dashboard] Safeguard against empty formula definitions

- datadog/resource_datadog_synthetics_test_.go
The field is optional so we'll get a panic if we try to fetch it while it's not present.
Closes #1836
> [datadog_synthetics_test] Check error when building token API authentication

- datadog/resource_datadog_dashboard.go
This can cause a crash, if we don't check for nil structs.
Closes #1841
> [datadog_dashboard] Handle empty section in template variables

- datadog/resource_datadog_synthetics_test_.go
Due to the different handling between API and browser tests, scheduling options were ignored.
Closes #1855
> [datadog_synthetics_test] Handle advanced scheduling in browser tests

- datadog/internal/validators/tags_set_is_nomalized.go
- datadog/internal/validators/tags_string_set_nomalized.go
Add helper that validate tags are normalized.
We previously dealt with such normalizations using the `DiffSuppressFunc` but this is currently not possible with the framework sdk. See issue: https://github.com/hashicorp/terraform-plugin-framework/issues/70
> [provider] Add helper to validate normalized tags

- datadog/resource_datadog_synthetics_test_.go
This PR puts in common the code used to set the options on Synthetics tests as well as the building of the local state for options. Currently this is done separately for api and browser tests, and this has led to several issues in the past where an option was added somewhere but forgotten in the other type.
> [datadog_synthetics_test] Refactor options for Synthetics tests

- datadog/resource_datadog_service_level_objective.go
Uses the sdk's experimental `GetRawConfig()` in order to check if the user is trying to remove a field.
In this case, because the field is optional and computed, removing the field in the config doesn't actually remove it in state - the terraform sdk keeps it around assuming it is computed. This causes issues if other fields conflict with the removed field, and there's no way to tell that the field is supposed to be removed (without checking the raw config) because the sdk reports the field as having not changed.
Resolves #1877 
Todo: check other resources for this interaction, good chance this exists elsewhere as well.
> [datadog_service_level_objective] Fix edge case removing fields that are both optional and computed

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
Some operators, for example `isUndefined` don't use the `targetvalue` field, but the field is marked as required in the terraform schema. This PR removes the required flag.
> [datadog_synthetics_test] Remove required from jsonpath and xpath targetvalue fields

- datadog/resource_datadog_dashboard_json.go
Handle an edge case where prepResource is called with nil config during refresh. 
Closes: https://github.com/DataDog/terraform-provider-datadog/issues/1897
> [datadog_dashboard_json] skip prepResource if attrMap is nil

- datadog/fwprovider/framework_provider.go
- datadog/provider.go
- docs/index.md
The old community client would leak keys when in debug mode when it tried to validate keys. This removes that call and replaces it with the official datadog go client, which properly redacts those keys. It also replaces the deprecated `NewTransport` because it logs http req/resp without regard for secrets.
Also updates docs to no longer mention that APP keys are validated. This is because the validate endpoint only validates the API key.
> [provider] Update API key validation call to use official SDK

- datadog/fwprovider/framework_provider.go
Prevents segfaulting when `api_url` is set to the empty string and there are no env vars to fall back on.
> [provider] Check for empty api_url string

- datadog/resource_datadog_logs_custom_pipeline.go
Fixes segfault due to empty string turning into a nil. The backend doesn't accept empty strings to begin with, so this adds a validate function as well as a nil check.
> [datadog_logs_custom_pipelines] Add empty string validation to grok parser samples list

- datadog/resource_datadog_logs_archive.go
IsSet() can return return true even if the associated value is nil. Let's check it to error out properly.
Closes #1909
> [datadog_logs_archive] Don't crash on empty logs archives destination

- datadog/fwprovider/framework_provider.go
`parseErr` is always nil if the edited code block is entered, so we cannot call `Error()` on it.
Fixes segfaults when the API url is missing protocol or host, such as `api.datadoghq.com` instead of `https://api.datadoghq.com`
> [provider] Fix segfault on invalid API URL

- docs/resources/synthetics_test.md
- examples/resources/datadog_synthetics_test/resource.tf
- Add missing uptime test example
- Standardise example blocks
When implementing datadog, I noticed there was no explicit example for an uptime test, which caused me to accidentally configure all uptime tests as `browser` tests instead of `api` tests.
Additionally, I noticed that some of the examples listed things like name, locations, and status towards the top, and others didn't. This caused me to write badly formatted code which I later had to go and correct once I realised what was possible.
This PR exemplifies good quality, readable, standardised code, and also adds a much needed example for uptime tests.
> [datadog_synthetics_test] Update and standardize example tests

- datadog/internal/utils/test_utils.go
errors.Is never returns true because our error structs don't implement the right `Is(error) bool` method. Changes the function to `errors.As` which doesn't solely rely on that method's implementation to check if error matches.
> [test_utils] Fix retry logic

- datadog/resource_datadog_integration_gcp.go
- docs/resources/integration_gcp.md
Updates the GCP Integration Terraform Resource. We want to mark it as deprecated because of the newly created gcp_sts resource.
> [datadog_integration_gcp] Mark resource as deprecated

- datadog/fwprovider/resource_datadog_spans_metric.go
- datadog/tests/resource_datadog_spans_metric_test.go
- docs/resources/spans_metric.md
group_by elements are sorted on the backend side so using a list forces you to order the elements on client side.
> [datadog_spans_metric] Convert `group_by` to set

- datadog/resource_datadog_dashboard.go
- datadog/resource_datadog_dashboard_json.go
- docs/resources/dashboard.md
- docs/resources/dashboard_json.md
This is a follow up to: https://github.com/DataDog/terraform-provider-datadog/issues/1974
Users should not combine usage of `dashboard_lists` reosurce and `dashboard_lists` attribute in dashboard resources as it will cause inconsistent behavior unless they are explicitly setup to ensure both values match. To avoid inconsistencies, users, should use either/or.
> [datadog_dashboard] Add note about tf managed dashboard lists when using `dashboard_lists` resource

- go.mod
- go.sum
> [provider] bump datadog-api-client Go SDK to v2.14.0

- datadog/resource_datadog_synthetics_test_.go
Synthetics tests with basic web auth work properly without a password set, but not when username is missing. Changes the requirement to only require username.
The password field is defined as required, but not nullable, so we can safely omit it and it will default to empty string on the go sdk side.
> [datadog_synthetics_test] Allow synthetics web basicauth without password set

- .github/workflows/test.yml
- .github/workflows/test_integration.yml
We need the terraform installed, and the default download has failed a fea times recently. Let's try to cache it.
> Cache terraform executable in integration tests

- datadog/fwprovider/resource_datadog_restriction_policy.go
- docs/resources/restriction_policy.md
* Update the documentation for restriction_policy resource to specify the required fields within `binding` object and other links
* Marked the `relation` and `principal` attribute as required for binding
* Added the note that dashboard resource type is not supported
* This is how the doc will look like for customers -> https://github.com/DataDog/terraform-provider-datadog/blob/sanjay.thakkar/GRACE-RP-Fix-Doc/docs/resources/restriction_policy.md
> [restriction_policy] Update restriction_policy resource documentation

- scripts/fmtcheck.sh
Check `exit code != 0` instead of log output being non-empty during terraform fmt
This fixes build failures due to `fmtcheck.sh` misinterpreting `terraform fmt`'s log output.
> Check exit code instead of log output during terraform fmt

- .github/CODEOWNERS
previously was only matching files in the /docs/ folder, instead of all subdirectories as well.
> [repo] Fix docs code ownership

- datadog/resource_datadog_sensitive_data_scanner_rule.go
Closes: https://github.com/DataDog/terraform-provider-datadog/issues/2040
> [datadog_sensitive_data_scanner_rule] Handle empty string for `excluded_namespaces`

- datadog/resource_datadog_dashboard.go
Backend can reset it to null when editing a dasboard.
Closes #2045
> [datadog_dashboard] Fix handling of nil notify_by list

- datadog/fwprovider/resource_datadog_spans_metric.go
- datadog/internal/planmodifiers/types_string_tag_normalizer.go
Add normalize tag plan modifier to handle diff caused by normalization in the backend.
Closes: https://github.com/DataDog/terraform-provider-datadog/issues/2052
> [datadog_spans_metric] Normalize tag value

- datadog/tests/data_source_datadog_sensitive_data_scanner_group_order_test.go
- datadog/tests/resource_datadog_sensitive_data_scanner_group_order_test.go
Fix flakiness when a data source is initialized with no groups in the system, and making sure a data source is initialized before trying to re-order groups
> [datadog_sensitive_data_scanner_group] Add ordering constraints to tests

- datadog/fwprovider/resource_datadog_dashboard_list.go
With sdk, we used to set id to nil on 404 with framework we need to remove the resource since ID is treated as an attribute
> [datadog_dashboard_list] Remove resource from state on 404

- datadog/resource_datadog_integration_azure.go
- docs/resources/integration_azure.md
We realized the doc comment for app_service_plan_filters in terraform has a typo, and could be generally improved by changing it to the doc we already use in the tile.
> [datadog_integration_azure] Fix docs for app_service_plan_filters

- datadog/fwprovider/resource_datadog_downtime_schedule.go
- datadog/resource_datadog_downtime.go
- docs/resources/downtime.md
- docs/resources/downtime_schedule.md
**Don't merge until Downtime V2 is enabled in us1.prod (targeted for 9/8/2023)**
Downtimes V2 will be enabled in all DCs by end of next week. This PR removes the unstable denotation for these endpoints.
> [datadog_downtime_schedule] GA the resource

- datadog/tests/resource_datadog_integration_aws_lambda_arn_test.go
- datadog/tests/resource_datadog_integration_aws_log_collection_test.go
Skip these tests as account id is not returned for new invalid AWS accounts which use `access_key_id`.
> Skip AWS log collection tests which use `access_key_id`

- datadog/resource_datadog_integration_aws_lambda_arn.go
- datadog/resource_datadog_integration_aws_log_collection.go
- datadog/resource_datadog_integration_aws_tag_filter.go
- docs/resources/integration_aws_lambda_arn.md
- docs/resources/integration_aws_log_collection.md
- docs/resources/integration_aws_tag_filter.md
`access_key_id` is no longer returned as `account_id` when creating AWS account using it. Lets update the documentation wording to make sure future users do not pass the `access_key_id` here
> [datadog_integration_aws_*] remove access_key_id note

- datadog/resource_datadog_service_definition_yaml.go
the order of the ci-pipeline-fingerprints isn't static, so keep the list sorted in state to prevent drift
Closes: #2117
> [datadog_service_definition_yaml] Keep `ci-pipeline-fingerprints` sorted in state

- datadog/resource_datadog_dashboard.go
We have a cast that doesn't work when the block is empty, let's check it.
Closes #2188
> [datadog_dashboard] Don't crash on empty group_by in widgets

- datadog/tests/data_source_datadog_ip_ranges_test.go
it wasn't possible for the old test to fail, the data source always creates an empty list/map for all fields, so testing if they exist is redundant.
> [datadog_ip_ranges] Fix test to actually test values in state

- datadog/resource_datadog_metric_metadata.go
- docs/resources/metric_metadata.md
Motivation
---------
It appears that metric API has enable the distribution type on metric metadata but the result between the `PUT` and the `GET` method is not consistent:
```bash
$ export metric_name=name_of_metric_distribution
$ curl -X PUT "https://api.datadoghq.com/api/v1/metrics/${metric_name}" \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-H "DD-API-KEY: ***" \
-H "DD-APPLICATION-KEY: ***" \
-d @- << EOF
{"type":"gauge"}
EOF
{"description":null,"short_name":null,"type":"gauge","unit":null,"per_unit":null,"statsd_interval":null,"integration":null}
and then the get:
$ curl -X GET "https://api.datadoghq.com/api/v1/metrics/${metric_name}" \
-H "Accept: application/json" \
-H "DD-API-KEY: ***" \
-H "DD-APPLICATION-KEY: ***" \ …
```
> [datadog_metric_metadata] correct consistency of type

- datadog/fwprovider/data_source_datadog_api_key.go
- datadog/fwprovider/data_source_datadog_application_key.go
- datadog/tests/data_source_datadog_api_key_test.go
- datadog/tests/data_source_datadog_application_key_test.go
- docs/data-sources/api_key.md
- docs/data-sources/application_key.md
If exact_match is true, searches the returned list of key names for an exact match instead of erroring out due to multiple results.
> [datadog_api_key][datadog_application_key] Add exact_match option to data sources

- datadog/resource_datadog_monitor.go
empty string is default for fields omitted in hcl, but that's not valid for the backend.
> [datadog_monitor] Omit recurrence start field if its an empty string

- CHANGELOG.md
The old link (#1281) is already found in an earlier entry on that list, and it doesn't have to do with `new_group_delay`.
> Fix link in old changelog entry

- datadog/resource_datadog_dashboard.go
- docs/resources/dashboard.md
This pull request increases limit for allowed graphs in split graph widget. 
It used to be 100, now 500
> [datadog_dashboards] Bump limit for allowed graphs in split graph widget

- datadog/resource_datadog_monitor.go
An empty search query is valid on the backend, remove this restriction on the terraform provider.
> [datadog_monitor] Sync search query validation with backend API

- datadog/resource_datadog_logs_index.go
make reset limit computed so it can be updated by the backend.
> [datadog_logs_index] Fix permadiff on omitted reset time

- datadog/resource_datadog_integration_pagerduty_service_object.go
- docs/resources/integration_pagerduty_service_object.md
- examples/resources/datadog_integration_pagerduty_service_object/import.sh
Adds an importer for `datadog_integration_pagerduty_service_object`.
As a way to get unstuck when there's an existing resource that is not reflected in the state.
With this, one can do:
```
terraform import datadog_integration_pagerduty_service_object.<name of the resource> "<service name>"
```
And get rid of `400 Bad Request` errors that might happen when applying on top of an already existing service with the same name.
Fixes #513 and #1822 (which shouldn't be closed, IMHO).
> [datadog_integration_pagerduty_service_object] Add importer

- datadog/resource_datadog_metric_metadata.go
This is similar to https://github.com/DataDog/terraform-provider-datadog/pull/2222
We've enabled the feature flag on our account, but because Datadog APIs don't allow including the `type: "distribution"` in the request payload anyway, update operations could end up with 400 bad request errors due to the upstream API validation.
This PR adds an interim workaround so that the provider doesn't include the `type` filed at all for any `distribution` metrics.
> [datadog_metric_metadata] don't send `type` field for distribution metrics

- datadog/resource_datadog_logs_archive.go
- docs/resources/logs_archive.md
[LOGSAC-468](https://datadoghq.atlassian.net/browse/LOGSAC-468)
Quick PR to reflect the public api change and make the project id an optional field in terraform as well
https://github.com/DataDog/datadog-api-spec/pull/2686
[LOGSAC-468]: https://datadoghq.atlassian.net/browse/LOGSAC-468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [datadog_logs_archive] Make project id optional in GCS destination

- datadog/resource_datadog_sensitive_data_scanner_group.go
fix the resource ignoring when the group is deleted on the backend
> [datadog_sensitive_data_scanner_group] Mark resource as missing when not found

- datadog/resource_datadog_logs_archive.go
- go.mod
- go.sum
Breaking changed happened [there](https://github.com/DataDog/datadog-api-client-go/commit/fd933f61ac8e295512f347f8f1e5a0b12bf51358), fixing it in this PR
> [datadog_logs_archive] Fix project id for logsArchive

- datadog/resource_datadog_user.go
Closes: https://github.com/DataDog/terraform-provider-datadog/issues/2292
> [datadog_users] Don't panic if no users is found

- datadog/resource_datadog_user.go
This PR proposes that we re-order role updates for datadog_user, so additions happen before removals.
I was testing `datadog_user` and ran into a funny case. If you're modifying yourself, for example to change from
```
[ datadog_role.old_admin_role.id ]
```
to
```
[ datadog_role.new_admin_role.id ]
```
... then if we do removals first, then additions, we'll get locked out and won't be able to finish the operation. It seems safer to first add all the new roles, then remove any old roles.
Note: it's still possible to delete your own role and lock yourself out, but only if the target list of roles doesn't contain the user_access_manage permission.
> [datadog_user] Re-order role updates

- datadog/fwprovider/resource_datadog_service_account_application_key.go
I got a bit confused about what had happened when apply errored and the error messages indicated it failed retrieving the key.
> [datadog_service_account_application_key] Improve service account application key error messages

- datadog/fwprovider/framework_provider.go
- docs/resources/integration_cloudflare_account.md
- examples/resources/datadog_integration_cloudflare_account/import.sh
Closes: https://github.com/DataDog/terraform-provider-datadog/issues/2342
> [framework_provider] handle empty import id

- datadog/resource_datadog_monitor_json.go
Fix the drift between POST and GET, but only for the missing case.
> [datadog_monitor_json] Ignore the POST null for the restriction_policy field

- docs/resources/synthetics_test.md
- examples/resources/datadog_synthetics_test/resource.tf
SYNTH-13888
We had a customer that tried to use the example in [the documentation](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test#example-usage) to create a synthetics GRPC test but it was failing.
We thought it was due to a lack of good error message, but it was actually because our example was not valid
- Update the example to make a valid grpc synthetics test
> [datadog_synthetics_documentation] Update synthetics GRPC example

- datadog/resource_datadog_synthetics_test_.go
SSIA, bugfix in response to customer ticket
> [datadog_synthetics_test] Ensure tags are non-empty and castable

- docs/resources/integration_fastly_service.md
- examples/resources/datadog_integration_fastly_service/import.sh
Fix import docs because fastly importing follows the `account-id:service-id` format
> [resource_integration_fastly_service] update import docs

- datadog/data_source_datadog_cloud_workload_security_agent_rules.go
- datadog/resource_datadog_cloud_workload_security_agent_rule.go
- docs/data-sources/cloud_workload_security_agent_rules.md
- docs/resources/cloud_workload_security_agent_rule.md
We want to surface the customers the `cloud_workload_security` resources are going to be deprecated soon, this PR updates the description to mention this.
> [CWS-2164] - Put the cloud workload security resources as deprecated

- datadog/data_source_datadog_cloud_workload_security_agent_rules.go
- datadog/resource_datadog_cloud_workload_security_agent_rule.go
- docs/data-sources/cloud_workload_security_agent_rules.md
- docs/resources/cloud_workload_security_agent_rule.md
On the previous PR, we updated the resource/datasource description to mention the `cloud_workload_security_agent_rules` resources are deprecated. 
This is adding a deprecation message to be prompted to customers when they run `terraform apply` or `terraform plan`
> Add deprecation message on cloud_workload_security_agent_rules resource and data source

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
It was not specified the parameter `browser_step.params.email` must be a JSON encoded string, as I discovered on my own.
> [datadog_synthetics_test] Fix docs for `browser_step.params.email`

- .github/CODEOWNERS
This PR confirms the change of ownership of the `datadog_synthetics_*` resources from @DataDog/synthetics-app to @DataDog/synthetics-ct.
> Synthetics CT takes ownership of the datadog_synthetics resources

- datadog/fwprovider/data_source_datadog_service_account.go
- docs/data-sources/service_account.md
https://datadoghq.atlassian.net/browse/ACCESS-2606
I modeled this off of the existing exact match filtering in `data_source_datadog_user`
Not sure whether I should match by name or email first, or whether it really even matters.
It didn't make sense to me to exact match by role, even if the filter string will filter for roles...
> [datadog_service_account] Implement exact match filtering

- docs/resources/synthetics_test.md
- examples/resources/datadog_synthetics_test/resource.tf
Add a second example for GRPC health test, distinct from GRPC behaviour test to clarify these two use cases.
> [datadog_synthetics_test] add grpc health test example in documentation

- datadog/fwprovider/resource_datadog_team_permission_setting.go
- datadog/internal/fwutils/fw_enrich_schema.go
- datadog/internal/validators/enum_validator.go
- docs/resources/synthetics_test.md
- docs/resources/team_permission_setting.md
- examples/resources/datadog_synthetics_test/resource.tf
Allows us to skip automatically generating the valid values list for enums in descriptions, for cases where extra context is needed.
Resolves: #2446
> [provider] Introduce a non-enriched enum validator for enum edge cases

- datadog/resource_datadog_authn_mapping.go
- datadog/tests/resource_datadog_authn_mapping_test.go
- docs/resources/authn_mapping.md
Based on our testing, only one of `role` and `team` should be provided for the resource to work as intended (https://github.com/DataDog/terraform-provider-datadog/issues/2148#issuecomment-2085167742).
This PR adds some validation to fix this.
Note that I have not tested this change, as I don't have a datadog org to test with.
> [datadog_authn_mapping] Only allow one of role and team to be set

- datadog/internal/validators/validators.go
- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
The synthetics resource now validates that the provided headers don't have new line characters 
fix #2462
> [datadog_synthetics_test] Add validation on synthetics test header

- datadog/fwprovider/data_source_datadog_service_account.go
- datadog/fwprovider/resource_datadog_service_account.go
- datadog/fwprovider/resource_datadog_user_role.go
- docs/data-sources/service_account.md
- docs/resources/service_account.md
- docs/resources/user_role.md
https://datadoghq.atlassian.net/browse/ACCESS-2568
`datadog_user_role` already allows for roles to be assigned to service accounts, luckily.
> [datadog_service_account] Role-assignment improvements for service accounts

- datadog/fwprovider/resource_datadog_application_key.go
- docs/resources/application_key.md
Add a new deprecation warning that Import will no longer be supported for application keys.
```
=> terraform plan
datadog_application_key.jackakeller-foo-application-import: Preparing import... [id=ed3f601f-94e0-463d-bd37-3867ce24a063]
datadog_application_key.jackakeller-foo-application-import: Refreshing state... [id=ed3f601f-94e0-463d-bd37-3867ce24a063]
Terraform will perform the following actions:
resource "datadog_application_key" "jackakeller-foo-application-import" {
id   = "ed3f601f-94e0-463d-bd37-3867ce24a063"
key  = (sensitive value)
name = "jackakeller-foo-application-import"
}
Plan: 1 to import, 0 to add, 0 to change, 0 to destroy.
╷
│ Warning: Deprecated
│
│ The import functionality for datadog_application_key resources is deprecated and will be removed in a future release …
```
> [datadog_application_key] Add deprecation warning for importing datadog_application_key resources

- datadog/fwprovider/data_source_datadog_application_key.go
- datadog/tests/data_source_datadog_application_key_test.go
- docs/data-sources/application_key.md
Add new deprecation message to datadog_application_key data source.
Followed these guidelines: https://developer.hashicorp.com/terraform/plugin/framework/deprecations#provider-data-source-or-resource-removal
Tested locally.
**Warning when deprecated data source is used:**
```
=> terraform plan
datadog_application_key.jackakeller-foo: Refreshing state... [id=ad77b716-c871-4e94-bb53-cef5ed244551]
data.datadog_application_key.foo: Reading...
data.datadog_application_key.foo: Read complete after 0s [id=ad77b716-c871-4e94-bb53-cef5ed244551]
No changes. Your infrastructure matches the configuration.
Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
╷
│ Warning: Deprecated
│
│   with data.datadog_application_key.foo,
│ …
```
> [datadog_application_key] Add deprecation warning to datadog_application_key data source

- datadog/fwprovider/resource_datadog_application_key.go
- datadog/tests/resource_datadog_application_key_test.go
When updating or importing application key resources, if the Datadog API does not include the optional computed `key` field, then the field is overwritten with an empty string in terraform state. The key is immutable so it does not need to be updated once it has been initially set.
Added a check to ensure the field is set before writing it into the response. 
Tested manually via integration test against API responses with and without the key field. Updated unit test to match new behavior and not depend on the API returning an optional field.
> [datadog_application_key] Stop overwriting key values in state when the API omits the key

- docs/resources/ip_allowlist.md
- examples/resources/datadog_ip_allowlist/resource.tf
I added an example to the ip_allowlist terraform docs that accidentally used a real IP address. This PR fixes the issue.
> [datadog_ip_allowlist] fix ip_allowlist code example error

- docs/resources/dashboard.md
- docs/resources/powerpack.md
- go.mod
- go.sum
https://datadoghq.atlassian.net/browse/DB-426
Updated documentation related to changes made by https://github.com/DataDog/datadog-api-spec/pull/2924
Because the `FormulaAndFunctionEventsDataSource` is [pulled directly](https://github.com/DataDog/terraform-provider-datadog/blob/master/datadog/resource_datadog_dashboard.go#L7331) from `datadog-api-spec`, related tests are in the `datadog-api-spec` repo and in this PR we only update the docs.
`go.mod` and `go.sum` include references to the unreleased version of the `datadog-api-spec-go` client.  #api-clients team says that:
> [datadog_dashboard] Update docs for new `incident_analytics` datasource

- .github/workflows/test.yml
merge queue didn't know what to do because CI checks weren't allowed to run on the temporary branches it created
> [repository] Enable ci for merge queue branches

- datadog/fwprovider/resource_datadog_service_account.go
- datadog/resource_datadog_user.go
- docs/resources/service_account.md
- docs/resources/user.md
`A list a role IDs` => `A list of role IDs`
I searched accross all repo files for this specific typo and edited all changes
> [datadog_service_account][datadog_user] Fix typo in service_account and user

- datadog/resource_datadog_synthetics_global_variable.go
- go.mod
- go.sum
This PR follows the latest change in datadog-api-spec, and use `syntheticsGlobalRequestVariable` instead of `syntheticsGlobalVariable`, the former being introduced by https://github.com/DataDog/datadog-api-spec/pull/2904.
> [SYNTH-15394] use new SyntheticsGlobalVariableRequest in global variable terraform resource

- .github/sdkv2-warning.yml
- .github/workflows/sdkv2_deprecation.yaml
- datadog/resource_something_new.go
Check for new sdkv2, failing any new `.go` files in the `datadog/` directory
> [repo] block sdkv2 resources

- datadog/fwprovider/data_source_datadog_api_key.go
- docs/data-sources/api_key.md
Add new deprecation message to datadog_api_key data source.
Followed these guidelines: https://developer.hashicorp.com/terraform/plugin/framework/deprecations#provider-data-source-or-resource-removal
Tested locally.
**Warning when deprecated data source is used**:
```sh
data.datadog_api_key.ddiner_test: Reading...
data.datadog_api_key.ddiner_test: Read complete after 1s [id=b4371e76-3361-4034-9b48-f15e7514587f]
No changes. Your infrastructure matches the configuration.
Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
╷
│ Warning: Deprecated
│
│   with data.datadog_api_key.ddiner_test,
│   on main.tf line 15, in data "datadog_api_key" "ddiner_test":
│   15: data "datadog_api_key" "ddiner_test" {
│
│ Deprecated. …
```
> [datadog_api_key] Add deprecation warning to datadog_api_key data source

- datadog/fwprovider/resource_datadog_api_key.go
- docs/resources/api_key.md
Add a new deprecation warning that Import will no longer be supported for application keys.
```sh
datadog_api_key.ddiner_test: Preparing import... [id=b4371e76-3361-4034-9b48-f15e7514587f]
datadog_api_key.ddiner_test: Refreshing state... [id=b4371e76-3361-4034-9b48-f15e7514587f]
Terraform will perform the following actions:
resource "datadog_api_key" "ddiner_test" {
id   = "b4371e76-3361-4034-9b48-f15e7514587f"
key  = (sensitive value)
name = "ddiner-test"
}
Plan: 1 to import, 0 to add, 0 to change, 0 to destroy.
╷
│ Warning: Deprecated
│
│ The import functionality for datadog_api_key resources is deprecated and will be removed in a future release with prior
│ notice. Securely store your API keys using a secret management system or use the datadog_api_key resource to create and
│ manage …
```
> [datadog_api_key] Add deprecation warning for importing datadog_api_key resources

- datadog/fwprovider/resource_datadog_api_key.go
- datadog/tests/resource_datadog_api_key_test.go
When updating or importing API key resources, if the Datadog API does not include the optional computed key field, then the field is overwritten with an empty string in terraform state. The key is immutable so it does not need to be updated once it has been initially set.
Added a check to ensure the field is set before writing it into the response.
Tested manually via integration test against API responses with and without the key field. Updated unit test to match new behavior and not depend on the API returning an optional field.
> [datadog_api_key] Stop overwriting key values in state when the API omits the key

- datadog/fwprovider/resource_datadog_restriction_policy.go
- datadog/tests/resource_datadog_restriction_policy_test.go
By not setting `state.Bindings` to an empty list if the attributes list is empty, we have a bug where if the policy was removed from a resource outside of terraform (manually in the UI, through the API, etc), it wouldn't be registered, and attempts to re-apply it would not detect a change.
Steps to reproduce the bug are:
1. Create a restriction policy using terraform
2. Delete the restriction policy in the UI
3. Run `terraform apply` again
Expected: The policy gets recreated
Actual: No differences are found, terraform succeeds with an empty apply.
Tested manually in a test env - confirmed that I could reproduce the original bug report, and that with this change, the policy was correctly reapplied in the same case.
> [datadog_restriction_policy] Allow policy deletions outside of terraform to prompt resource recreation

- datadog/resource_datadog_dashboard.go
- go.mod
- go.sum
There was a change to the api-spec in https://github.com/DataDog/datadog-api-spec/pull/2745 which included breaking client changes to how the `Widget.TIME` was represented.  
This PR is based on the latest go sdk version, and adjusts the default `LiveSpan` to using the `WidgetLegacyLiveSpan` wrapper class.  This is purely to unblock new releases of `terraform-provider-datadog`, and does not include Terraform support for the new `WidgetNewLiveSpan` and `WidgetNewFixedSpan` time types.
> Extended Widget Time - reconcile WidgetLegacyLiveSpan with new clients

- datadog/resource_datadog_synthetics_test_.go
- go.mod
- go.sum
Resolves: #2564 #2561 
The root issue is the backend returning both `int` and `string` values, when the client sdk is only expecting a `string`. This updates the tf provider to use a newly introduced oneOf wrapper to handle both cases internally, while only exposing the field as a `string` to the end user.
> [datadog_synthetics_test] Handle both integer and string values for port

- datadog/internal/validators/validators.go
- datadog/internal/validators/validators_test.go
After https://github.com/DataDog/terraform-provider-datadog/pull/2469, the following Terraform definition:
```tf
resource "datadog_synthetics_test" "test" {
[...]
request_headers = {
":authority" = "example.com"
}
[...]
}
```
Is failing with:
```
│ Error: invalid value for request_headers (header field must be a valid token)
│
│ with datadog_synthetics_test.test,
│ on modules/uptime-monitoring/main.tf line 51, in resource "datadog_synthetics_test" "test":
│ 51: request_headers = {
│ 52: ":authority" = "example.com"
│ 54: }
```
> [datadog_synthetics_test] Fix http2 pseudo-headers not accepted

- datadog/resource_datadog_synthetics_test_.go
On import, previous state does not exist so we cannot rely on the previous state to set the old values in state for example and pattern. 
Stack trace:
```
➜  ~/Documents/terraform terraform plan -generate-config-out=generated3.tf
datadog_synthetics_test.test_integration_installation: Preparing import... [id=123]
datadog_synthetics_test.test_integration_installation: Refreshing state... [id=123]
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
Stack trace from the terraform-provider-datadog_v3.46.0 plugin:
panic: runtime error: index out of range [0] with length 0
goroutine 134 …
```
> [datadog_synthetics_test] Handle secure `config_variables` on import

- datadog/fwprovider/resource_datadog_integration_cloudflare_account.go
- docs/resources/integration_cloudflare_account.md
Lets remove the default to avoid overriding remote current resources config as well as update the doc to clarify it. Followup to https://github.com/DataDog/terraform-provider-datadog/issues/2656
> [datadog_cloudflare] Remove default and update doc

- docs/resources/dashboard.md
- docs/resources/powerpack.md
- go.mod
- go.sum
> [datadog_dashboard][datadog_powerpack] Update go client to support `good_minutes` and `bad_minutes` for Time Slice SLOs

- docs/resources/integration_aws_tag_filter.md
- go.mod
- go.sum
bump go client to include the changes in https://github.com/DataDog/datadog-api-client-go/pull/2788
address https://github.com/DataDog/terraform-provider-datadog/issues/2669
> [datadog_integration_aws_tag_filter] include `step_functions` as valid enum for v1 AWS tag filter 

- datadog/resource_datadog_monitor_json.go
- datadog/tests/cassettes/TestAccDatadogMonitorJSONBasic.yaml
- datadog/tests/cassettes/TestAccDatadogMonitorJSONImport.yaml
This hacks around this (already hacky) resource having conflicts with the restricted_roles attribute when the restriction_policy resource is used to manage permissions on monitors. The general strategy is to ignore roles sent back from the API if roles are not explicitly defined in the monitor. Note: This resource should be converted to a framework provider resource, that should provide much easier access to what the user configured and make this handling consistent and esaier to reason about.
Scenarios tested:
* create monitor and restriction_policy (with and without roles), there should be no diff when running subsequent plans
* modify the monitor and restricton policy, e.g. add/remove a role, there should be no diffs when running subsequent plans
Open questions:
* what does this do to …
> [resource_monitor_json] Avoid restricted role diffs with restriction_policy

- datadog/fwprovider/resource_datadog_webhook.go
SSIA, the field is computed, so it can be non-null while still not having a valid value for the enum.
> [datadog_webhook] Fix panic on missing encode_as field

- datadog/tests/data_source_datadog_application_key_test.go
- datadog/tests/resource_datadog_application_key_test.go
- datadog/tests/resource_datadog_domain_allowlist_test.go
ApplicationKeyDatasource is deprecated
DatadogApplicationKey_Update no longer returns a key value, no point in comparing anymore
TestAccDatadogDomainAllowlist_CreateUpdate replay only due to 2 second backend replication delay
> [provider_test] skip a bunch of failing tests

- datadog/resource_datadog_synthetics_test_.go
Initially, we wanted to implement all auth methods used by api tests for browser tests in terraform. Turns out that dogweb only supports web basic auth for browser tests, and as a side effect, also NTLM and Digest which also use `username` and `password`.  We thus added a comment to explain that in terraform.
> [datadog_synthetics_test] Add comment regarding browser step available auths

- .github/CODEOWNERS
What does this PR do?
---------------------
- Update code ownership to contain specific logs-backend teams. This is in preparation for the deprecation of #logs-backend slack channel, to ensure all code is owned by at least one of the four sub-teams.
- Not associated with any story.
> Update Logs code ownership to specific teams

- docs/resources/integration_aws_tag_filter.md
- go.mod
- go.sum
SSIA, bump it as far as we can without hitting the synthetics breaking change
> [provider] Bump Datadog Go SDK

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
Update the documentation of Synthetics with maximum values for retry and interval
> [datadog_synthetics_test] Add maximum value in docs for retry and interval

- datadog/data_source_datadog_sensitive_data_scanner_standard_pattern.go
- docs/data-sources/sensitive_data_scanner_standard_pattern.md
- docs/resources/synthetics_test.md
Align the `datadog_sensitive_data_standard_pattern` resource with the [Public API to list standard patterns](https://docs.datadoghq.com/api/latest/sensitive-data-scanner/#list-standard-patterns)
- Add `description` attribute.
- Deprecate the `pattern` attribute.
- [Jira ticket](https://datadoghq.atlassian.net/browse/SDS-405?atlOrigin=eyJpIjoiNzM5MzQ3MDQ1MmFlNDRlY2FhMTZmOGYyZGZhYTdhYjciLCJwIjoiaiJ9)
> [datadog_sensitive_data_standard_pattern] add description and deprecate pattern

- .github/workflows/changelog.yaml
- .github/workflows/prepare_release.yml
- .github/workflows/release.yml
- Replaces usage of `tibdex/github-app-token` with official GitHub action
> fix(github-workflows): use official GitHub action for token generation

- .github/workflows/test.yml
- datadog/provider.go
skip `fmtcheck` when running tofu tests
> testacc when testing tofu

- datadog/fwprovider/resource_datadog_integration_cloudflare_account.go
- docs/resources/integration_cloudflare_account.md
> [datadog_integration_cloudflare_account] Don't set email left empty and ignore resource order

- datadog/resource_datadog_monitor.go
- docs/resources/monitor.md
Resolves https://github.com/DataDog/terraform-provider-datadog/issues/2679
This value should be optional, defaulted to false. It should not be marked as computed.
> [datadog_monitor] Change enable_samples to optional

- datadog/resource_datadog_synthetics_test_.go
This PR prevents updating the `files` param from the upload file step in browser tests, to keep next plans stable.
Without this, the next plans keep trying to align the state returned by the backend and the local config:
```
~ files      = jsonencode(
~ [
~ {
- bucketKey = "browser-upload-file-step/72e-vim-wme/2024-12-17T13:05:48.286579_f235f491-4dfd-4fbd-96ae-ed1b233b3e41.json"
+ content   = "this is the new new test content"
name      = "test file"
},
]
)
```
> [datadog_synthetics_test] Prevent updating `files` with the backend response to keep the plan stable

- docs/resources/integration_aws_account.md
- examples/resources/datadog_integration_aws_account/import.sh
Fixes an incorrect statement in the import docs. The old `datadog_integration_aws` account `id` value cannot be used to import to the new `datadog_integration_aws_account` resource; it must be the Datadog UUID.
Reported by issue: https://github.com/DataDog/terraform-provider-datadog/issues/2733
> [datadog_integration_aws_account] Fix incorrect import docs instructions

- .github/workflows/test.yml
- datadog/fwprovider/resource_datadog_webhook.go
`terraform import` of existing webhooks was failing because id was read from `state.Name`, which is null when importing a resource
> [datadog_webhook] fix import 

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
- go.mod
- go.sum
Following https://github.com/DataDog/datadog-api-spec/pull/3074, this PR adds the `public_id` as a computed field of the browser steps.
> [datadog_synthetics_test] Add step public id in the state

- datadog/fwprovider/resource_datadog_integration_aws_account.go
Raised here: https://github.com/DataDog/terraform-provider-datadog/issues/2747
`resources_config` is a required block, but we weren't
- validating that exactly one block was defined
- handling the case where the block is nil
This fix adds validation to ensure the block is present to match the expectation defined in the docs.
> [datadog_integration_aws_account] Fix panic when resources_config is omitted

- datadog/fwprovider/resource_datadog_azure_integration.go
- docs/resources/integration_azure.md
Reverts DataDog/terraform-provider-datadog#2738
Sorry, didn't mean to merge this so soon.
> Revert "[AZINTS-2487] Update Azure integration terraform to support metric filitering"

- datadog/fwprovider/data_source_datadog_application_key.go
- datadog/fwprovider/resource_datadog_application_key.go
- datadog/tests/resource_datadog_application_key_test.go
- docs/data-sources/application_key.md
- docs/resources/application_key.md
This PR allows users to manage (create/update) scoped app keys in Terraform
Tested manually with:
```
resource "datadog_application_key" "app_key_1" {
name = "willson tf scoped app key test"
scopes = ["dashboards_read", "dashboards_write"]
}
```
Also verified that an invalid scope in the list results in a 400.
> [datadog_application_key] Support scoped app key management

- datadog/fwprovider/resource_datadog_api_key.go
- datadog/fwprovider/resource_datadog_application_key.go
App keys are not returned by the API after creation, so we should save the previous state values to avoid the `Provider returned invalid result object after apply` and overwrite of state value with null
Tested by creating an application key and updating its name
> [datadog_application_key] use plan modifiers for app keys

- .github/CODEOWNERS
- datadog/fwprovider/resource_datadog_api_key.go
API keys are not returned by the API after creation, so we should save the previous state values to avoid the `Provider returned invalid result object after apply` and overwrite of state value with null.
Tested by creating an application key and updating its name.
> [datadog_api_key] Use plan modifier for API keys.

- datadog/fwprovider/data_source_datadog_application_key.go
- docs/data-sources/application_key.md
fixes regression caused by https://github.com/DataDog/terraform-provider-datadog/pull/2760, which added scopes to the Schema but not the model or state update
> [data_datadog_application_key] remove scopes from schema

- datadog/fwprovider/resource_datadog_azure_integration.go
- docs/resources/integration_azure.md
reintroduces changes reverted in DataDog/terraform-provider-datadog#2778
> [datadog_azure_integration] Support metric filtering

- datadog/fwprovider/resource_datadog_service_account_application_key.go
- datadog/tests/resource_datadog_application_key_test.go
- datadog/tests/resource_datadog_service_account_application_key_test.go
- docs/resources/service_account_application_key.md
Similar to https://github.com/DataDog/terraform-provider-datadog/pull/2760, but for service accounts.
Tested manually with:
```
resource "datadog_service_account" "foo" {
email = "new@example.com"
name  = "terraform test"
}
resource "datadog_service_account_application_key" "foo" {
service_account_id = datadog_service_account.foo.id
name               = "terraform test app key"
scopes             = ["dashboards_write"]
}
```
Also verified that an invalid scope in the list results in a 400.
> [datadog_application_key] Support scoped app key management for service accounts

- datadog/fwprovider/resource_datadog_service_account.go
Closes #2736 
**Current behaviour**
If you ask for a service_account without roles 
```
resource "datadog_service_account" "bar" {
email = "etienne.carriere@datadoghq.com"
name  = "Terraform test"
}
```
the drift will never be detected : 
* At the creation, as there is no role defined, `state.Roles` is null
* If there is a manual change on `service-account` object by adding a role, at the next refresh of state, the state.Roles is still null and will not be refreshed 
If you ask a service_account with at least one role, the issue doesn't happens as the State will not be null 
Similarly if you import a service_account, Roles will never be loaded 
**Proposed behavior** 
Update in all cases  the state.Roles from the result so we : 
* better detect drift 
* there is no false "update in place" …
> [datadog_service_account] Fix : `roles` attribute is now always updated

- datadog/resource_datadog_service_definition_yaml.go
Fixes #2801 
Prevents conversion without check so there is no panic if people describe service catalog with contact having "nil" attribute.
> [datadog_service_definition_yaml] Fix panic when contact attributes exists but are empty (nil)

- datadog/resource_datadog_synthetics_global_variable.go
When creating the resource 
```hcl
resource "datadog_synthetics_global_variable" "test_variable" {
name        = "EXAMPLE_VARIABLE"
description = "Description of the variable"
tags        = ["foo:bar", "env:test"]
value       = "variable-value"
}
```
the following drift was always present 
```
Terraform will perform the following actions:
~ resource "datadog_synthetics_global_variable" "test_variable" {
id               = "xxx"
name             = "EXAMPLE_VARIABLE"
tags             = [
"foo:bar",
"env:test",
]
- options {
- totp_parameters {}
}
}
```
This PR removes this unwanted drift
> [datadog_synthetics_global_variable] Remove drift on `option` argument

- datadog/resource_datadog_service_definition_yaml.go
- go.mod
- go.sum
https://github.com/DataDog/terraform-provider-datadog/pull/2802 changed the sorting of contact attributes in `datadog_service_definition_yaml`. Since the backend can reorder attributes, we need to compare them directly instead of just testing for equality 
This was missed in the original PR review because the `TestAccDatadogServiceDefinition_Order` test was not run
> check comparison instead of equality

- .generator/src/generator/templates/utils/state_helper.j2
- .generator/src/generator/type.py
Some fields in the schema generation that should be required are not tagged as such in the generated resources.
The 'required' field was ignored and all attributes in a schema were marked as optional.
Changed the name of the checked field.
> [Generator] (fix) Fixed schema generation

- datadog/fwprovider/data_source_datadog_api_key.go
- datadog/fwprovider/data_source_datadog_teams.go
- datadog/fwprovider/resource_datadog_api_key.go
- datadog/tests/resource_datadog_api_key_test.go
- docs/data-sources/api_key.md
- docs/resources/api_key.md
Fixes: #1875 
This PR allows to manage the `remote_config_read_enabled` on datadog_api_key . It is used for [remote config](https://docs.datadoghq.com/agent/remote_config/?tab=configurationyamlfile) feature. 
Specific point : the default value at API level is true (which is a not standard logic) so we need to have a true default value at resource level
As the test is not eligible for cassettes, I run `RECORD=none TESTARGS="-run TestAccDatadogApiKey_Update" make testall" and the test was fine.
> [datadog_api_key] Support `remote_config_read_enabled` argument

- .generator/src/generator/setup.py
- .generator/src/generator/templates/utils/request_builder_helper.j2
- .generator/src/generator/templates/utils/resource_test_helper.j2
- .generator/src/generator/templates/utils/schema_helper.j2
- .generator/src/generator/templates/utils/state_helper.j2
- .generator/src/generator/utils.py
In order to produce `datadog_shared_dashboard` resource, here is some fixes to the generator : https://github.com/DataDog/terraform-provider-datadog/pull/2838
Use scaffolding generator to create shared dashboard resource and apply the following changes : 
* fix `required` logic : the required field can be either : 
* an array (at the parent object) : https://json-schema.org/understanding-json-schema/reference/object#required
* a boolean field (at the field level) : https://swagger.io/docs/specification/v3_0/describing-parameters/#required-and-optional-parameters 
* improve `enum` logic : For enum,  it is needed from/to cast to the base type
* add `read_only` logic : For field being a `read-only` field, it should be Computed only field 
* add `nullable` logic : For field being a …
> Fix generator to take in account `required` / `enum` / `read_only` / `nullable` cases

- datadog/data_source_datadog_user.go
- docs/data-sources/user.md
It is the equivalent of #2786 but for the `datadog_user` datasource
> [datadog_user] Add computed attributes to `datadog_user` datasource

- datadog/fwprovider/resource_datadog_api_key.go
- datadog/tests/resource_datadog_api_key_test.go
- docs/resources/api_key.md
Fixes #2847 
Remove config is configured globally at org level (see /organization-settings/remote-config). 
* When it is not enabled, the `remote_config_read_enabled` argument of api_key is always set to `false` 
* When it is enabled, the `remote_config_read_enabled` argument is set by default to `true` but can be set explicitly to `false`
Proposed fix : 
* When the user don't set `remote_config_read_enabled` , it will be the default value (true if RC is enabled, false if not) . Similar behavior as in <3.55.0
* When the user set `remote_config_read_enabled` to `false` , it will always works 
* When the user set `remote_config_read_enabled` to `true`, 
* it will succeeds if RC is enabled at org level 
* it will fails if RC is not enabled at org level
You will get this error if you set the …
> [datadog_api_key] Fix bug introduced in 3.55.0 for organisation that doesn't have Remove config enabled

- datadog/fwprovider/resource_datadog_openapi_api.go
- docs/resources/openapi_api.md
This resource is deprecated, use the software catalog resource intead.
> [datadog_openapi_api] Deprecate openapi resource

- .generator/src/generator/formatter.py
- .generator/src/generator/setup.py
- .generator/src/generator/templates/utils/state_helper.j2
- .generator/src/generator/utils.py
Strings with the 'format' fields set to 'date-time' were being read as strings.
Meanwhile the Go client automatically converts them to `*time.Time` and breaks the updateState function.
Such fields are now properly converted back to strings when updating the state.
- Added a new formatting function and filter to support date-time enrichment
- Changed the generation to use this filter
- Tidied `.generator/src/generator/utils.py`
> [Generator] (fix) Support date-time format enrichment

- .github/workflows/test.yml
Reverting the change as the current approach doesn't work well with non standard name tests.
> Run entire test suite for all PR's

- datadog/resource_datadog_synthetics_test_.go
Since the merge of https://github.com/DataDog/terraform-provider-datadog/pull/2820, the Terraform provider for the API has been consistently expecting the `renotify_interval` option. This pull request modifies the behavior to ignore the `renotify_occurrences` option if the `renotify_interval` is not set.
> [datadog_synthetics_test] Only set renotify_occurrences if renotify_interval is set 

- datadog/resource_datadog_dashboard.go
- docs/resources/dashboard.md
- docs/resources/powerpack.md
I noticed after https://github.com/DataDog/terraform-provider-datadog/pull/2856 got merged that we had five instances of a line that read:
```
- `cell_display_mode` (List of String) A list of display modes for each table cell. List items one of `number`, `bar`. Valid values are `number`, `bar`, `trend`.
```
I thought it didn't make sense that `trend` would be a valid value, but not a list item. This PR ~adds `trend` as one of the items in all five instances~ removes those duplicate lists.
> [datadog_dashboard] Remove duplicate accepted values in table cell display mode docs

- datadog/resource_datadog_role.go
- docs/resources/role.md
- scripts/generate-docs.sh
We have rolled out the ability for customers to remove restricted permissions from their roles. This change updates the Terraform Provider docs so that customers can make these changes in Terraform.
> [resource_datadog_role] Update terraform docs to include default_permissions_opt_out attribute

- .generator/README.md
- .generator/src/generator/cli.py
- .generator/src/generator/formatter.py
- .generator/src/generator/openapi.py
- .generator/src/generator/setup.py
- .generator/src/generator/templates/data_source/base.j2
- .generator/src/generator/templates/data_source/read.j2
- .generator/src/generator/templates/data_source/schema.j2
- .generator/src/generator/templates/data_source/state.j2
- .generator/src/generator/templates/data_source/types.j2
- .generator/src/generator/templates/read_method.j2
- .generator/src/generator/templates/update_state_method.j2
- .generator/src/generator/templates/utils/schema_helper.j2
- .generator/src/generator/templates/utils/state_helper.j2
- .generator/src/generator/type.py
- .generator/src/generator/utils.py
The generator Is currently able to generate a resource, adding a way to generate datasources seemed natural.
- updated readme
- added datasource templates
- added datasource generation
> [Generator] (feat) Added datasource generation

- .generator/src/generator/openapi.py
When a user does not specify resources or datasources to be generated, the generator crashes.
Adding a default value of `[]` to each solves the problem.
- Added a default value when  no resources or datasource config is provided
- Added documentation to the 'get_data_sources' function
> [Generator] (fix) Made resources and datasource optional

- datadog/fwprovider/resource_datadog_spans_metric.go
- datadog/tests/resource_datadog_spans_metric_test.go
This occurs in the event of tag_name being normalized (e.g. from uppercase to lowercase). When that occurs, TF will mark include_percentiles as unknown, since it's a calculated field. We know that in this case nothing should happen though.
Should fix #2888
> [datadog_spans_metric] Suppress unknown include_percentiles state

- .github/workflows/changelog.yaml
Remove retrieval of github token, since it's not needed and causes PRs coming from forks to fail the check.
One such example is https://github.com/DataDog/terraform-provider-datadog/pull/2822
Tested with a `changelog/feature` label and observed it failing the check correctly at https://github.com/DataDog/terraform-provider-datadog/actions/runs/14110718575/job/39528403961
> Remove need for github-token when validating PR title

- datadog/fwprovider/resource_datadog_software_catalog.go
- datadog/internal/fwutils/fw_enrich_schema.go
- datadog/internal/fwutils/fw_enrich_schema_test.go
- datadog/internal/validators/cidr_ip_validator.go
- datadog/internal/validators/entity_yaml_validator.go
- datadog/internal/validators/validators.go
- datadog/internal/validators/validators_test.go
- docs/resources/action_connection.md
- docs/resources/apm_retention_filter.md
- docs/resources/app_builder_app.md
- docs/resources/ip_allowlist.md
- docs/resources/software_catalog.md
- docs/resources/synthetics_concurrency_cap.md
- docs/resources/synthetics_global_variable.md
- docs/resources/workflow_automation.md
Some validators did not have an description enrichment set up. This PRs aims to add description enrichment that takes into account more validators.
Enrichment added for the following validators: 
- `oneOfValidator`
-  `regexMatchesValidator`
- `ValidEntityYAMLValidator`
- `cidrIpValidator`
- `lengthAtLeastValidator`
- `betweenValidator`
- `atLeastValidator`
> [Doc] (feat) added  description enrichment for more validators

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
The maximum value showed in the documentation for `retry` is incorrect, leading to confusion because users can get validation errors because of it.
This PR fixes that.
> [datadog_synthetics_test] Fix retry maximum value

- datadog/tests/data_source_datadog_app_builder_app_test.go
- datadog/tests/resource_datadog_app_builder_app_test.go
- docs/resources/synthetics_test.md
- examples/resources/datadog_synthetics_test/resource.tf
**What's New:**
ICMP Test Example: Demonstrates how to configure an ICMP test using the provider.
> [datadog_synthetics_test] Add an example for ICMP testing

- docs/resources/synthetics_test.md
- examples/resources/datadog_synthetics_test/resource.tf
**What's New:**
Updated Assertions Examples: Replaced non-functional gRPC step assertions with correct and allowed versions.
> [datadog_synthetics_test] Fix example for GRPC testing

- datadog/resource_datadog_synthetics_test_.go
A past bug in Datadog UI corrupted the value of `compressedProtoFile` for gRPC tests or multistep API tests with gRPC step(s).
This field should be zlib-compressed then base64-encoded. Unfortunately, the past UI bug made it so that when updating an synthetics test in the UI, the `compressedProtoFile` was only base64-encoded.
While the issue is now fixed at UI level, we have to handle corrupted tests by accepting without error both a b64 or a zlib+b64 field.
> [datadog_synthetics_tests] Fix encoding bug on plain_proto_file / compressedProtoFile

- .generator/src/generator/templates/base_resource.j2
- .generator/src/generator/templates/data_source/base.j2
- .generator/src/generator/templates/resource_test.j2
Following what was done in [this PR](https://github.com/DataDog/datadog-api-client-go/pull/3013); for example [here](https://github.com/DataDog/datadog-api-client-go/pull/3013/files#diff-f417b890deaaf37ed96b02f52142614d7e89ecfab0c7e0f1e17c1eb70c2edd4eR16) to remove dash from generated DD go client; strip the "-" when using go client sdk for generated terraform provider..
> [Generator] Remove "-" from generated golang api reference

- datadog/fwprovider/data_source_datadog_synthetics_locations.go
- docs/resources/synthetics_test.md
- examples/resources/datadog_synthetics_test/resource.tf
This PR updates the comments in the Datadog Synthetics Test resource example to explicitly state that the size parameter in file uploads is measured in bytes.
> [datadog_synthetics_test] Specify the unit in the example for file upload

- .generator/src/generator/type.py
The generator crashed when a schema does not have any properties. This can happen if a resource creation allows for query parameters instead.
- Changed the way we access the "properties" field.
> [Generator] Fixed generator crash

- datadog/resource_datadog_dashboard.go
- docs/dashboard_widget_field_rules.md
- docs/resources/dashboard.md
- docs/resources/powerpack.md
This PR adds support for custom links in treemap widgets, allowing users to add clickable links to their treemap visualizations.
- Added `custom_links` field to treemap widget schema
- Implemented custom links support in both directions (Terraform ↔ Datadog)
No breaking changes. This is a backward-compatible enhancement that adds optional functionality to treemap widgets.
1. Create a dashboard with a treemap widget using this configuration:
```hcl
resource "datadog_dashboard" "example_dashboard" {
title        = "Example Dashboard with Treemap"
description  = "Dashboard demonstrating treemap widget with custom links"
layout_type  = "ordered"
widget {
treemap_definition {
request {
query {
metric_query {
query = "avg:system.cpu.user{*} by {host}"
name  = "cpu_usage"
}
}
formula { …
```
> [datadog_dashboards] [datadog_powerpacks] add custom_links support to treemap widgets

- datadog/internal/utils/utils.go
- datadog/resource_datadog_cloud_configuration_rule.go
- docs/resources/cloud_configuration_rule.md
In Terraform lists are a sequence of values in which order matters . Sets are unordered collection of unique values.
We are currently trying to add default_tags to the `datadog_cloud_configuration_rule` resource and the orderness of the list type is currently blocking us. 
This change will unblock #2969 
- Changed the type of the `tags` field to `schema.TypeList`
- added a `GetStringSliceFromSet` function to have an alternative to `GetStringSlice` which only applies to slices
> [datadog_cloud_configuration_rule] Changed tags field type to Set

- .github/workflows/sdkv2_deprecation.yaml
Forks workflows can't post comments to the PR due to token restrictions, so currently the job just fails due to lacking permissions to post a comment on the PR and doesn't explain why. This should at least make it more obvious.
> Log error for sdkv2 deprecation check

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
Adds a link to the official Datadog API documentation for the `locations` field in the Synthetics resource. This improves the clarity of the field by pointing users directly to locations id+name.
- Updated `locations` field description in the schema.
- Updated corresponding `.md` documentation file.
- [SYNTH-19809] Update location array examples in Synthetics terraform docs
[SYNTH-19809]: https://datadoghq.atlassian.net/browse/SYNTH-19809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [synthetics_test] Add API endpoint link to synthetics location list

- datadog/fwprovider/resource_datadog_app_builder_app.go
- docs/resources/app_builder_app.md
- Updates resource description to mention export button for visibility. This aligns with Workflow's description: https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/workflow_automation
- Original PR: https://github.com/DataDog/terraform-provider-datadog/pull/2723
- Ticket: https://datadoghq.atlassian.net/browse/APPS-2302
> [datadog_app_builder_app] Mention export button in description

- datadog/data_source_datadog_monitors.go
Fixes #2782 
It is quite idiomatic with terraform datasources to have 2 datasources : 
* a singular one (`datadog_monitor` in our case) that will fails if the search criteria matches 0 or more than 1 results 
* a plural one (`datadog_monitors` in our case) that will not fails based on the number of items matching the search criteria as it returns an array. 
this PR implement this policy if there is no monitors matched.
> [datadog_monitors] Fix `datadog_monitors` datasource not failing if no monitors found

- .goreleaser.yml
The `goreleaser.yml` had some deprecated or missing fields.
- Added a version field
- Replaced the archives.format field by archives.formats
> [Chore] Updated the goreleaser.yml file

- datadog/resource_datadog_synthetics_test_.go
We fixed a bug recently where assertion targets were not being set as numbers correctly, but fixing that caused another bug with TLS versions specifically which can't be numbers
> [datadog_synthetics_test] Exclude TLS version types from being converted to number

- datadog/fwprovider/resource_datadog_synthetics_private_location.go
- datadog/tests/resource_datadog_synthetics_private_location_test.go
- docs/resources/synthetics_private_location.md
This PR adds support for the API key field in the private location resource, in response to [this issue](https://github.com/DataDog/terraform-provider-datadog/issues/1636).
This field is only used to generate the PL configuration at resource creation.
> [synthetics_test] Add private location api key field

- datadog/fwprovider/resource_datadog_integration_aws_account.go
- docs/resources/integration_aws_account.md
Addresses docs issue raised in https://github.com/DataDog/terraform-provider-datadog/issues/3032
> [APIR-1709][resource_datadog_integration_aws_account] Update docs for logs_config.lambda_forwarder.sources field

- datadog/resource_datadog_synthetics_test_.go
- go.mod
- go.sum
This PR fixes an [issue](https://github.com/DataDog/terraform-provider-datadog/issues/2952) where importing a test with a missing password in basic auth would result in a go client error.
We modified the client to make `username` and `password` as optional, in [this PR](https://github.com/DataDog/datadog-api-client-go/pull/3163).
> [datadog_synthetics_test] Fix basic auth

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
- examples/resources/datadog_synthetics_test/resource.tf
Fixes #2626 
This PR fixes the documentation and example about the browser step params `element` field, which should be a JSON encoded string.
> [datadog_synthetics_test] Fix browser step params element documentation

- go.mod
- go.sum
Bumping the Datadog Go client to `2.43.0` to get latest updates on logs pipelines and add the support for logs array processor, solving the issue that users may face when using the `datadog_logs_pipelines` datasource which can't parse these new processors and fail silently.
> [datadog_logs_pipelines] Updates Datadog Go API client to v2.43.0

- datadog/resource_datadog_synthetics_test_.go
- docs/resources/synthetics_test.md
This PR adds diagnostics for common mistakes when migrating an API test that was previously terraformed to do 1 thing, into a multistep API test that does this same thing + some extra steps.
For example, here I copied the previous logic and pasted it into an `api_step`, but forgot to remove the leftover `request_definition` and `assertion` at the root:
Another common mistake is forgetting to update the `subtype` to `multi`. In that case, here is the error:
This PR only impacts `type = "api"` tests, in `resourceDatadogSyntheticsTestCreate` and `resourceDatadogSyntheticsTestUpdate`.
> [datadog_synthetics_test] Add QoL feedback when converting multistep API test

- datadog/fwprovider/observability_pipeline/amazon_s3_destination.go
- datadog/fwprovider/observability_pipeline/aws_auth.go
- datadog/fwprovider/resource_datadog_observability_pipeline.go
- datadog/tests/resource_datadog_observability_pipeline_test.go
Fix - Including the Amazon S3 destination which was already within the API Spec
API Implementation was in this commit https://github.com/DataDog/datadog-api-spec/pull/3807/commits/161e7ffc1dcbe79f385afa7763ade4c261f03555
> [datadog_observability_pipeline] Amazon S3 Destination

- datadog/fwprovider/data_source_datadog_workflow_automation.go
- datadog/fwprovider/resource_datadog_workflow_automation.go
This is a common practice for terraform resources / data sources. It was a miss on my part when I made this resource. We need to be cleaning up from our state when we receive not found so we don't lock the user out of using Terraform.
> [workflow_automation] Clean up state if workflow not found

- docs/resources/on_call_team_routing_rules.md
- examples/resources/datadog_on_call_team_routing_rules/import.sh
There's a typo in the Terraform provider documentation for [datadog_on_call_team_routing_rules](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/on_call_team_routing_rules). 
In the Import section, the comment currently says: `# Import an existing on_call_schedule`
This comment appears to be a copy-paste from the `on_call_schedule` resource and should refer to `on_call_team_routing_rules` instead.
> [datadog_on_call_team_routing_rules] Fix incorrect comment in import section of the documentation

- .github/ISSUE_TEMPLATE/01-bug-report.yml
- .github/workflows/test.yml
- .github/workflows/test_integration.yml
Bumps the version of terraform and opentofu executables used in CI for tests and integration tests to latest currently available.
The github required checks should also be updated once this is ok.
> [provider] Use latest stable terraform/opentofu in CI

- docs/resources/integration_aws_account.md
Currently rendered docs are broken due to this missing `"`.
This example is not auto-generated by `make docs` since it's in the [exclusion list](https://github.com/DataDog/terraform-provider-datadog/blob/9a686fc93093533def3f4a955e77e121c3074144/scripts/generate-docs.sh#L6).
> [datadog_integration_aws_account] Fix missing double quotes breaking docs rendering

- datadog/fwprovider/resource_datadog_restriction_policy.go
- docs/resources/restriction_policy.md
Update documentation to note that restriction policy resource can be used with monitors, it should be requested.
> [datadog_restriction_policy] Update comment for usage with monitors

- datadog/fwprovider/resource_datadog_security_monitoring_rule_json.go
- docs/resources/security_monitoring_default_rule.md
Align with Terraform’s **Required** attribute contract: **echo the planned `json` bytes on Create/Update**, and perform **semantic filtering only in Read** to avoid false diffs when Datadog adds defaults.
* **Create/Update**
* No re-encoding. Persist the planned `json` value verbatim.
* **Read**
* Build `filtered = filterToUserFields(user, api)` (drops API-only/default fields, keeps user-provided keys).
* **Semantic compare**: `reflect.DeepEqual(filtered, userRule)`.
* Only if different, write `filtered` back. Otherwise, keep existing bytes.
* `json` is **Required** → must round-trip **byte-for-byte** across apply.
* Re-marshalling in Create/Update changed key order/whitespace/newline → **“Provider produced inconsistent result after apply.”**
* Filtering remains necessary to handle …
> [datadog_security_monitoring_rule] Defer JSON filtering to Read to fix “inconsistent result after apply”

- go.mod
Accidentally added [here](https://github.com/DataDog/terraform-provider-datadog/pull/3252/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R107) - ran `make update-go-client` to pull latest package version and had this locally without realizing it
> [chore] Remove accidental replace for datadog-api-client-go in go.mod

- datadog/fwprovider/resource_datadog_csm_threats_agent_rule.go
When users define CSM Threats Agent Rule expressions using heredoc syntax (`<<EOF`) or with trailing spaces, Terraform shows "Provider produced inconsistent result after apply" error because the backend trims whitespace but the provider doesn't.
Fixed by using `TrimSpaceStringValue` custom type for the `expression` field, which provides semantic equality that compares trimmed values.
> [datadog_csm_threats] Fix csm threats agent rule expression whitespace inconsistency
